-- Gui to Lua
-- Version: 3.2

-- Instances:

local CosmeticsBAA = Instance.new("ScreenGui")
local CosmeticsMainFrame = Instance.new("Frame")
local OC = Instance.new("TextButton")
local Logo = Instance.new("ImageLabel")
local AxeHandleMaterial = Instance.new("TextButton")
local BallMaterial = Instance.new("TextButton")
local BallColor = Instance.new("TextButton")
local Ball = Instance.new("TextLabel")
local AxeHandle = Instance.new("TextLabel")
local AxeColor = Instance.new("TextButton")
local AxeMaterial = Instance.new("TextButton")
local Axe = Instance.new("TextLabel")
local AxeHandleColor = Instance.new("TextButton")
local BallMaterialSelect = Instance.new("ScrollingFrame")
local Plastic = Instance.new("TextButton")
local Wood = Instance.new("TextButton")
local Slate = Instance.new("TextButton")
local Concrete = Instance.new("TextButton")
local UIGridLayout = Instance.new("UIGridLayout")
local CorrodedMetal = Instance.new("TextButton")
local DiamondPlate = Instance.new("TextButton")
local Foil = Instance.new("TextButton")
local Grass = Instance.new("TextButton")
local Ice = Instance.new("TextButton")
local Marble = Instance.new("TextButton")
local Granite = Instance.new("TextButton")
local Brick = Instance.new("TextButton")
local Pebble = Instance.new("TextButton")
local Sand = Instance.new("TextButton")
local Fabric = Instance.new("TextButton")
local SmoothPlastic = Instance.new("TextButton")
local Metal = Instance.new("TextButton")
local WoodPlanks = Instance.new("TextButton")
local Cobblestone = Instance.new("TextButton")
local Air = Instance.new("TextButton")
local Water = Instance.new("TextButton")
local Rock = Instance.new("TextButton")
local Glacier = Instance.new("TextButton")
local Snow = Instance.new("TextButton")
local Sandstone = Instance.new("TextButton")
local Mud = Instance.new("TextButton")
local Basalt = Instance.new("TextButton")
local Ground = Instance.new("TextButton")
local CrackedLava = Instance.new("TextButton")
local Neon = Instance.new("TextButton")
local Glass = Instance.new("TextButton")
local Asphalt = Instance.new("TextButton")
local LeafyGrass = Instance.new("TextButton")
local Salt = Instance.new("TextButton")
local Limestone = Instance.new("TextButton")
local Pavement = Instance.new("TextButton")
local ForceField = Instance.new("TextButton")
local Default = Instance.new("TextButton")
local AxeMaterialSelect = Instance.new("ScrollingFrame")
local Plastic_2 = Instance.new("TextButton")
local Wood_2 = Instance.new("TextButton")
local Slate_2 = Instance.new("TextButton")
local Concrete_2 = Instance.new("TextButton")
local UIGridLayout_2 = Instance.new("UIGridLayout")
local CorrodedMetal_2 = Instance.new("TextButton")
local DiamondPlate_2 = Instance.new("TextButton")
local Foil_2 = Instance.new("TextButton")
local Grass_2 = Instance.new("TextButton")
local Ice_2 = Instance.new("TextButton")
local Marble_2 = Instance.new("TextButton")
local Granite_2 = Instance.new("TextButton")
local Brick_2 = Instance.new("TextButton")
local Pebble_2 = Instance.new("TextButton")
local Sand_2 = Instance.new("TextButton")
local Fabric_2 = Instance.new("TextButton")
local SmoothPlastic_2 = Instance.new("TextButton")
local Metal_2 = Instance.new("TextButton")
local WoodPlanks_2 = Instance.new("TextButton")
local Cobblestone_2 = Instance.new("TextButton")
local Air_2 = Instance.new("TextButton")
local Water_2 = Instance.new("TextButton")
local Rock_2 = Instance.new("TextButton")
local Glacier_2 = Instance.new("TextButton")
local Snow_2 = Instance.new("TextButton")
local Sandstone_2 = Instance.new("TextButton")
local Mud_2 = Instance.new("TextButton")
local Basalt_2 = Instance.new("TextButton")
local Ground_2 = Instance.new("TextButton")
local CrackedLava_2 = Instance.new("TextButton")
local Neon_2 = Instance.new("TextButton")
local Glass_2 = Instance.new("TextButton")
local Asphalt_2 = Instance.new("TextButton")
local LeafyGrass_2 = Instance.new("TextButton")
local Salt_2 = Instance.new("TextButton")
local Limestone_2 = Instance.new("TextButton")
local Pavement_2 = Instance.new("TextButton")
local ForceField_2 = Instance.new("TextButton")
local Default_2 = Instance.new("TextButton")
local AxeHandleMaterialSelect = Instance.new("ScrollingFrame")
local Plastic_3 = Instance.new("TextButton")
local Wood_3 = Instance.new("TextButton")
local Slate_3 = Instance.new("TextButton")
local Concrete_3 = Instance.new("TextButton")
local UIGridLayout_3 = Instance.new("UIGridLayout")
local CorrodedMetal_3 = Instance.new("TextButton")
local DiamondPlate_3 = Instance.new("TextButton")
local Foil_3 = Instance.new("TextButton")
local Grass_3 = Instance.new("TextButton")
local Ice_3 = Instance.new("TextButton")
local Marble_3 = Instance.new("TextButton")
local Granite_3 = Instance.new("TextButton")
local Brick_3 = Instance.new("TextButton")
local Pebble_3 = Instance.new("TextButton")
local Sand_3 = Instance.new("TextButton")
local Fabric_3 = Instance.new("TextButton")
local SmoothPlastic_3 = Instance.new("TextButton")
local Metal_3 = Instance.new("TextButton")
local WoodPlanks_3 = Instance.new("TextButton")
local Cobblestone_3 = Instance.new("TextButton")
local Air_3 = Instance.new("TextButton")
local Water_3 = Instance.new("TextButton")
local Rock_3 = Instance.new("TextButton")
local Glacier_3 = Instance.new("TextButton")
local Snow_3 = Instance.new("TextButton")
local Sandstone_3 = Instance.new("TextButton")
local Mud_3 = Instance.new("TextButton")
local Basalt_3 = Instance.new("TextButton")
local Ground_3 = Instance.new("TextButton")
local CrackedLava_3 = Instance.new("TextButton")
local Neon_3 = Instance.new("TextButton")
local Glass_3 = Instance.new("TextButton")
local Asphalt_3 = Instance.new("TextButton")
local LeafyGrass_3 = Instance.new("TextButton")
local Salt_3 = Instance.new("TextButton")
local Limestone_3 = Instance.new("TextButton")
local Pavement_3 = Instance.new("TextButton")
local ForceField_3 = Instance.new("TextButton")
local Default_3 = Instance.new("TextButton")
local BallColorSelect = Instance.new("ScrollingFrame")
local UIGridLayout_4 = Instance.new("UIGridLayout")
local White = Instance.new("TextButton")
local Red = Instance.new("TextButton")
local Crimson = Instance.new("TextButton")
local Cyan = Instance.new("TextButton")
local Yellow = Instance.new("TextButton")
local Green = Instance.new("TextButton")
local Pink = Instance.new("TextButton")
local Purple = Instance.new("TextButton")
local Blue = Instance.new("TextButton")
local Lime = Instance.new("TextButton")
local Gray = Instance.new("TextButton")
local Brown = Instance.new("TextButton")
local Tan = Instance.new("TextButton")
local AxeHandleColorSelect = Instance.new("ScrollingFrame")
local UIGridLayout_5 = Instance.new("UIGridLayout")
local White_2 = Instance.new("TextButton")
local Red_2 = Instance.new("TextButton")
local Crimson_2 = Instance.new("TextButton")
local Cyan_2 = Instance.new("TextButton")
local Yellow_2 = Instance.new("TextButton")
local Green_2 = Instance.new("TextButton")
local Pink_2 = Instance.new("TextButton")
local Purple_2 = Instance.new("TextButton")
local Blue_2 = Instance.new("TextButton")
local Lime_2 = Instance.new("TextButton")
local Gray_2 = Instance.new("TextButton")
local Brown_2 = Instance.new("TextButton")
local Tan_2 = Instance.new("TextButton")
local Default_4 = Instance.new("TextButton")
local AxeColorSelect = Instance.new("ScrollingFrame")
local UIGridLayout_6 = Instance.new("UIGridLayout")
local White_3 = Instance.new("TextButton")
local Red_3 = Instance.new("TextButton")
local Crimson_3 = Instance.new("TextButton")
local Cyan_3 = Instance.new("TextButton")
local Yellow_3 = Instance.new("TextButton")
local Green_3 = Instance.new("TextButton")
local Pink_3 = Instance.new("TextButton")
local Purple_3 = Instance.new("TextButton")
local Blue_3 = Instance.new("TextButton")
local Lime_3 = Instance.new("TextButton")
local Gray_3 = Instance.new("TextButton")
local Brown_3 = Instance.new("TextButton")
local Tan_3 = Instance.new("TextButton")
local Default_5 = Instance.new("TextButton")

--Properties:

CosmeticsBAA.Name = "Cosmetics BAA"
CosmeticsBAA.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
CosmeticsBAA.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

CosmeticsMainFrame.Name = "Cosmetics Main Frame"
CosmeticsMainFrame.Parent = CosmeticsBAA
CosmeticsMainFrame.Active = true
CosmeticsMainFrame.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
CosmeticsMainFrame.BackgroundTransparency = 0.650
CosmeticsMainFrame.Position = UDim2.new(0.202478707, 0, 0.365891457, 0)
CosmeticsMainFrame.Size = UDim2.new(0, 483, 0, 333)

OC.Name = "OC"
OC.Parent = CosmeticsMainFrame
OC.BackgroundColor3 = Color3.fromRGB(255, 6, 10)
OC.BackgroundTransparency = 0.550
OC.Position = UDim2.new(0.907000005, 0, 0.0209999997, 0)
OC.Size = UDim2.new(0, 38, 0, 34)
OC.Font = Enum.Font.SourceSans
OC.Text = ">"
OC.TextColor3 = Color3.fromRGB(255, 255, 255)
OC.TextSize = 30.000

Logo.Name = "Logo"
Logo.Parent = CosmeticsMainFrame
Logo.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Logo.Position = UDim2.new(0.00999999978, 0, 0.0149999997, 0)
Logo.Size = UDim2.new(0, 100, 0, 100)
Logo.Image = "rbxasset://textures/ui/GuiImagePlaceholder.png"

AxeHandleMaterial.Name = "Axe Handle Material"
AxeHandleMaterial.Parent = CosmeticsMainFrame
AxeHandleMaterial.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
AxeHandleMaterial.BackgroundTransparency = 0.700
AxeHandleMaterial.Position = UDim2.new(0, 123, 0, 183)
AxeHandleMaterial.Size = UDim2.new(0, 150, 0, 50)
AxeHandleMaterial.Font = Enum.Font.SourceSans
AxeHandleMaterial.Text = "Material: Default"
AxeHandleMaterial.TextColor3 = Color3.fromRGB(255, 255, 255)
AxeHandleMaterial.TextSize = 23.000

BallMaterial.Name = "Ball Material"
BallMaterial.Parent = CosmeticsMainFrame
BallMaterial.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
BallMaterial.BackgroundTransparency = 0.700
BallMaterial.Position = UDim2.new(0, 123, 0, 108)
BallMaterial.Size = UDim2.new(0, 150, 0, 50)
BallMaterial.Font = Enum.Font.SourceSans
BallMaterial.Text = "Material: Default"
BallMaterial.TextColor3 = Color3.fromRGB(255, 255, 255)
BallMaterial.TextSize = 23.000

BallColor.Name = "Ball Color"
BallColor.Parent = CosmeticsMainFrame
BallColor.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
BallColor.BackgroundTransparency = 0.700
BallColor.Position = UDim2.new(0, 283, 0, 108)
BallColor.Size = UDim2.new(0, 150, 0, 50)
BallColor.Font = Enum.Font.SourceSans
BallColor.Text = "Color: Nil"
BallColor.TextColor3 = Color3.fromRGB(255, 255, 255)
BallColor.TextSize = 23.000

Ball.Name = "Ball"
Ball.Parent = CosmeticsMainFrame
Ball.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ball.BackgroundTransparency = 0.700
Ball.Position = UDim2.new(0, 13, 0, 108)
Ball.Size = UDim2.new(0, 100, 0, 50)
Ball.Font = Enum.Font.SourceSans
Ball.Text = "Ball:"
Ball.TextColor3 = Color3.fromRGB(255, 255, 255)
Ball.TextSize = 23.000

AxeHandle.Name = "Axe Handle"
AxeHandle.Parent = CosmeticsMainFrame
AxeHandle.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
AxeHandle.BackgroundTransparency = 0.700
AxeHandle.Position = UDim2.new(0, 13, 0, 183)
AxeHandle.Size = UDim2.new(0, 100, 0, 50)
AxeHandle.Font = Enum.Font.SourceSans
AxeHandle.Text = "Axe Handle:"
AxeHandle.TextColor3 = Color3.fromRGB(255, 255, 255)
AxeHandle.TextSize = 23.000

AxeColor.Name = "Axe Color"
AxeColor.Parent = CosmeticsMainFrame
AxeColor.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
AxeColor.BackgroundTransparency = 0.700
AxeColor.Position = UDim2.new(0, 283, 0, 258)
AxeColor.Size = UDim2.new(0, 150, 0, 50)
AxeColor.Font = Enum.Font.SourceSans
AxeColor.Text = "Color: Default"
AxeColor.TextColor3 = Color3.fromRGB(255, 255, 255)
AxeColor.TextSize = 23.000

AxeMaterial.Name = "Axe Material"
AxeMaterial.Parent = CosmeticsMainFrame
AxeMaterial.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
AxeMaterial.BackgroundTransparency = 0.700
AxeMaterial.Position = UDim2.new(0, 123, 0, 258)
AxeMaterial.Size = UDim2.new(0, 150, 0, 50)
AxeMaterial.Font = Enum.Font.SourceSans
AxeMaterial.Text = "Material: Default"
AxeMaterial.TextColor3 = Color3.fromRGB(255, 255, 255)
AxeMaterial.TextSize = 23.000

Axe.Name = "Axe"
Axe.Parent = CosmeticsMainFrame
Axe.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Axe.BackgroundTransparency = 0.700
Axe.Position = UDim2.new(0, 13, 0, 258)
Axe.Size = UDim2.new(0, 100, 0, 50)
Axe.Font = Enum.Font.SourceSans
Axe.Text = "Axe:"
Axe.TextColor3 = Color3.fromRGB(255, 255, 255)
Axe.TextSize = 23.000

AxeHandleColor.Name = "Axe Handle Color"
AxeHandleColor.Parent = CosmeticsMainFrame
AxeHandleColor.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
AxeHandleColor.BackgroundTransparency = 0.700
AxeHandleColor.Position = UDim2.new(0, 283, 0, 183)
AxeHandleColor.Size = UDim2.new(0, 150, 0, 50)
AxeHandleColor.Font = Enum.Font.SourceSans
AxeHandleColor.Text = "Color: Default"
AxeHandleColor.TextColor3 = Color3.fromRGB(255, 255, 255)
AxeHandleColor.TextSize = 23.000

BallMaterialSelect.Name = "Ball Material Select"
BallMaterialSelect.Parent = CosmeticsBAA
BallMaterialSelect.Active = true
BallMaterialSelect.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
BallMaterialSelect.BackgroundTransparency = 0.650
BallMaterialSelect.Position = UDim2.new(0.417974383, 0, 0.311627924, 0)
BallMaterialSelect.Size = UDim2.new(0, 229, 0, 243)
BallMaterialSelect.Visible = false
BallMaterialSelect.CanvasSize = UDim2.new(0, 0, 0, 0)

Plastic.Name = "Plastic"
Plastic.Parent = BallMaterialSelect
Plastic.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Plastic.BackgroundTransparency = 0.700
Plastic.Size = UDim2.new(0, 200, 0, 50)
Plastic.Font = Enum.Font.SourceSans
Plastic.Text = "Plastic"
Plastic.TextColor3 = Color3.fromRGB(255, 255, 255)
Plastic.TextSize = 40.000

Wood.Name = "Wood"
Wood.Parent = BallMaterialSelect
Wood.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Wood.BackgroundTransparency = 0.700
Wood.Size = UDim2.new(0, 200, 0, 50)
Wood.Font = Enum.Font.SourceSans
Wood.Text = "Wood"
Wood.TextColor3 = Color3.fromRGB(255, 255, 255)
Wood.TextSize = 40.000

Slate.Name = "Slate"
Slate.Parent = BallMaterialSelect
Slate.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Slate.BackgroundTransparency = 0.700
Slate.Size = UDim2.new(0, 200, 0, 50)
Slate.Font = Enum.Font.SourceSans
Slate.Text = "Slate"
Slate.TextColor3 = Color3.fromRGB(255, 255, 255)
Slate.TextSize = 40.000

Concrete.Name = "Concrete"
Concrete.Parent = BallMaterialSelect
Concrete.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Concrete.BackgroundTransparency = 0.700
Concrete.Size = UDim2.new(0, 200, 0, 50)
Concrete.Font = Enum.Font.SourceSans
Concrete.Text = "ConCrete"
Concrete.TextColor3 = Color3.fromRGB(255, 255, 255)
Concrete.TextSize = 40.000

UIGridLayout.Parent = BallMaterialSelect
UIGridLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIGridLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout.CellPadding = UDim2.new(0, 0, 0, 5)
UIGridLayout.CellSize = UDim2.new(0, 200, 0, 50)

CorrodedMetal.Name = "CorrodedMetal"
CorrodedMetal.Parent = BallMaterialSelect
CorrodedMetal.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
CorrodedMetal.BackgroundTransparency = 0.700
CorrodedMetal.Size = UDim2.new(0, 200, 0, 50)
CorrodedMetal.Font = Enum.Font.SourceSans
CorrodedMetal.Text = "CorrodedMetal"
CorrodedMetal.TextColor3 = Color3.fromRGB(255, 255, 255)
CorrodedMetal.TextSize = 40.000

DiamondPlate.Name = "DiamondPlate"
DiamondPlate.Parent = BallMaterialSelect
DiamondPlate.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
DiamondPlate.BackgroundTransparency = 0.700
DiamondPlate.Size = UDim2.new(0, 200, 0, 50)
DiamondPlate.Font = Enum.Font.SourceSans
DiamondPlate.Text = "DiamondPlate"
DiamondPlate.TextColor3 = Color3.fromRGB(255, 255, 255)
DiamondPlate.TextSize = 40.000

Foil.Name = "Foil"
Foil.Parent = BallMaterialSelect
Foil.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Foil.BackgroundTransparency = 0.700
Foil.Size = UDim2.new(0, 200, 0, 50)
Foil.Font = Enum.Font.SourceSans
Foil.Text = "Foil"
Foil.TextColor3 = Color3.fromRGB(255, 255, 255)
Foil.TextSize = 40.000

Grass.Name = "Grass"
Grass.Parent = BallMaterialSelect
Grass.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Grass.BackgroundTransparency = 0.700
Grass.Size = UDim2.new(0, 200, 0, 50)
Grass.Font = Enum.Font.SourceSans
Grass.Text = "Grass"
Grass.TextColor3 = Color3.fromRGB(255, 255, 255)
Grass.TextSize = 40.000

Ice.Name = "Ice"
Ice.Parent = BallMaterialSelect
Ice.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ice.BackgroundTransparency = 0.700
Ice.Size = UDim2.new(0, 200, 0, 50)
Ice.Font = Enum.Font.SourceSans
Ice.Text = "Ice"
Ice.TextColor3 = Color3.fromRGB(255, 255, 255)
Ice.TextSize = 40.000

Marble.Name = "Marble"
Marble.Parent = BallMaterialSelect
Marble.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Marble.BackgroundTransparency = 0.700
Marble.Size = UDim2.new(0, 200, 0, 50)
Marble.Font = Enum.Font.SourceSans
Marble.Text = "Marble"
Marble.TextColor3 = Color3.fromRGB(255, 255, 255)
Marble.TextSize = 40.000

Granite.Name = "Granite"
Granite.Parent = BallMaterialSelect
Granite.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Granite.BackgroundTransparency = 0.700
Granite.Size = UDim2.new(0, 200, 0, 50)
Granite.Font = Enum.Font.SourceSans
Granite.Text = "Granite"
Granite.TextColor3 = Color3.fromRGB(255, 255, 255)
Granite.TextSize = 40.000

Brick.Name = "Brick"
Brick.Parent = BallMaterialSelect
Brick.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Brick.BackgroundTransparency = 0.700
Brick.Size = UDim2.new(0, 200, 0, 50)
Brick.Font = Enum.Font.SourceSans
Brick.Text = "Brick"
Brick.TextColor3 = Color3.fromRGB(255, 255, 255)
Brick.TextSize = 40.000

Pebble.Name = "Pebble"
Pebble.Parent = BallMaterialSelect
Pebble.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pebble.BackgroundTransparency = 0.700
Pebble.Size = UDim2.new(0, 200, 0, 50)
Pebble.Font = Enum.Font.SourceSans
Pebble.Text = "Pebble"
Pebble.TextColor3 = Color3.fromRGB(255, 255, 255)
Pebble.TextSize = 40.000

Sand.Name = "Sand"
Sand.Parent = BallMaterialSelect
Sand.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Sand.BackgroundTransparency = 0.700
Sand.Size = UDim2.new(0, 200, 0, 50)
Sand.Font = Enum.Font.SourceSans
Sand.Text = "Sand"
Sand.TextColor3 = Color3.fromRGB(255, 255, 255)
Sand.TextSize = 40.000

Fabric.Name = "Fabric"
Fabric.Parent = BallMaterialSelect
Fabric.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Fabric.BackgroundTransparency = 0.700
Fabric.Size = UDim2.new(0, 200, 0, 50)
Fabric.Font = Enum.Font.SourceSans
Fabric.Text = "Fabric"
Fabric.TextColor3 = Color3.fromRGB(255, 255, 255)
Fabric.TextSize = 40.000

SmoothPlastic.Name = "SmoothPlastic"
SmoothPlastic.Parent = BallMaterialSelect
SmoothPlastic.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
SmoothPlastic.BackgroundTransparency = 0.700
SmoothPlastic.Size = UDim2.new(0, 200, 0, 50)
SmoothPlastic.Font = Enum.Font.SourceSans
SmoothPlastic.Text = "SmoothPlastic"
SmoothPlastic.TextColor3 = Color3.fromRGB(255, 255, 255)
SmoothPlastic.TextSize = 40.000

Metal.Name = "Metal"
Metal.Parent = BallMaterialSelect
Metal.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Metal.BackgroundTransparency = 0.700
Metal.Size = UDim2.new(0, 200, 0, 50)
Metal.Font = Enum.Font.SourceSans
Metal.Text = "Metal"
Metal.TextColor3 = Color3.fromRGB(255, 255, 255)
Metal.TextSize = 40.000

WoodPlanks.Name = "WoodPlanks"
WoodPlanks.Parent = BallMaterialSelect
WoodPlanks.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
WoodPlanks.BackgroundTransparency = 0.700
WoodPlanks.Size = UDim2.new(0, 200, 0, 50)
WoodPlanks.Font = Enum.Font.SourceSans
WoodPlanks.Text = "WoodPlanks"
WoodPlanks.TextColor3 = Color3.fromRGB(255, 255, 255)
WoodPlanks.TextSize = 40.000

Cobblestone.Name = "Cobblestone"
Cobblestone.Parent = BallMaterialSelect
Cobblestone.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Cobblestone.BackgroundTransparency = 0.700
Cobblestone.Size = UDim2.new(0, 200, 0, 50)
Cobblestone.Font = Enum.Font.SourceSans
Cobblestone.Text = "Cobblestone"
Cobblestone.TextColor3 = Color3.fromRGB(255, 255, 255)
Cobblestone.TextSize = 40.000

Air.Name = "Air"
Air.Parent = BallMaterialSelect
Air.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Air.BackgroundTransparency = 0.700
Air.Size = UDim2.new(0, 200, 0, 50)
Air.Font = Enum.Font.SourceSans
Air.Text = "Air"
Air.TextColor3 = Color3.fromRGB(255, 255, 255)
Air.TextSize = 40.000

Water.Name = "Water"
Water.Parent = BallMaterialSelect
Water.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Water.BackgroundTransparency = 0.700
Water.Size = UDim2.new(0, 200, 0, 50)
Water.Font = Enum.Font.SourceSans
Water.Text = "Water"
Water.TextColor3 = Color3.fromRGB(255, 255, 255)
Water.TextSize = 40.000

Rock.Name = "Rock"
Rock.Parent = BallMaterialSelect
Rock.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Rock.BackgroundTransparency = 0.700
Rock.Size = UDim2.new(0, 200, 0, 50)
Rock.Font = Enum.Font.SourceSans
Rock.Text = "Rock"
Rock.TextColor3 = Color3.fromRGB(255, 255, 255)
Rock.TextSize = 40.000

Glacier.Name = "Glacier"
Glacier.Parent = BallMaterialSelect
Glacier.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Glacier.BackgroundTransparency = 0.700
Glacier.Size = UDim2.new(0, 200, 0, 50)
Glacier.Font = Enum.Font.SourceSans
Glacier.Text = "Glacier"
Glacier.TextColor3 = Color3.fromRGB(255, 255, 255)
Glacier.TextSize = 40.000

Snow.Name = "Snow"
Snow.Parent = BallMaterialSelect
Snow.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Snow.BackgroundTransparency = 0.700
Snow.Size = UDim2.new(0, 200, 0, 50)
Snow.Font = Enum.Font.SourceSans
Snow.Text = "Snow"
Snow.TextColor3 = Color3.fromRGB(255, 255, 255)
Snow.TextSize = 40.000

Sandstone.Name = "Sandstone"
Sandstone.Parent = BallMaterialSelect
Sandstone.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Sandstone.BackgroundTransparency = 0.700
Sandstone.Size = UDim2.new(0, 200, 0, 50)
Sandstone.Font = Enum.Font.SourceSans
Sandstone.Text = "Sandstone"
Sandstone.TextColor3 = Color3.fromRGB(255, 255, 255)
Sandstone.TextSize = 40.000

Mud.Name = "Mud"
Mud.Parent = BallMaterialSelect
Mud.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Mud.BackgroundTransparency = 0.700
Mud.Size = UDim2.new(0, 200, 0, 50)
Mud.Font = Enum.Font.SourceSans
Mud.Text = "Mud"
Mud.TextColor3 = Color3.fromRGB(255, 255, 255)
Mud.TextSize = 40.000

Basalt.Name = "Basalt"
Basalt.Parent = BallMaterialSelect
Basalt.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Basalt.BackgroundTransparency = 0.700
Basalt.Size = UDim2.new(0, 200, 0, 50)
Basalt.Font = Enum.Font.SourceSans
Basalt.Text = "Basalt"
Basalt.TextColor3 = Color3.fromRGB(255, 255, 255)
Basalt.TextSize = 40.000

Ground.Name = "Ground"
Ground.Parent = BallMaterialSelect
Ground.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ground.BackgroundTransparency = 0.700
Ground.Size = UDim2.new(0, 200, 0, 50)
Ground.Font = Enum.Font.SourceSans
Ground.Text = "Ground"
Ground.TextColor3 = Color3.fromRGB(255, 255, 255)
Ground.TextSize = 40.000

CrackedLava.Name = "CrackedLava"
CrackedLava.Parent = BallMaterialSelect
CrackedLava.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
CrackedLava.BackgroundTransparency = 0.700
CrackedLava.Size = UDim2.new(0, 200, 0, 50)
CrackedLava.Font = Enum.Font.SourceSans
CrackedLava.Text = "CrackedLava"
CrackedLava.TextColor3 = Color3.fromRGB(255, 255, 255)
CrackedLava.TextSize = 40.000

Neon.Name = "Neon"
Neon.Parent = BallMaterialSelect
Neon.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Neon.BackgroundTransparency = 0.700
Neon.Size = UDim2.new(0, 200, 0, 50)
Neon.Font = Enum.Font.SourceSans
Neon.Text = "Neon"
Neon.TextColor3 = Color3.fromRGB(255, 255, 255)
Neon.TextSize = 40.000

Glass.Name = "Glass"
Glass.Parent = BallMaterialSelect
Glass.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Glass.BackgroundTransparency = 0.700
Glass.Size = UDim2.new(0, 200, 0, 50)
Glass.Font = Enum.Font.SourceSans
Glass.Text = "Glass"
Glass.TextColor3 = Color3.fromRGB(255, 255, 255)
Glass.TextSize = 40.000

Asphalt.Name = "Asphalt"
Asphalt.Parent = BallMaterialSelect
Asphalt.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Asphalt.BackgroundTransparency = 0.700
Asphalt.Size = UDim2.new(0, 200, 0, 50)
Asphalt.Font = Enum.Font.SourceSans
Asphalt.Text = "Asphalt"
Asphalt.TextColor3 = Color3.fromRGB(255, 255, 255)
Asphalt.TextSize = 40.000

LeafyGrass.Name = "LeafyGrass"
LeafyGrass.Parent = BallMaterialSelect
LeafyGrass.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
LeafyGrass.BackgroundTransparency = 0.700
LeafyGrass.Size = UDim2.new(0, 200, 0, 50)
LeafyGrass.Font = Enum.Font.SourceSans
LeafyGrass.Text = "LeafyGrass"
LeafyGrass.TextColor3 = Color3.fromRGB(255, 255, 255)
LeafyGrass.TextSize = 40.000

Salt.Name = "Salt"
Salt.Parent = BallMaterialSelect
Salt.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Salt.BackgroundTransparency = 0.700
Salt.Size = UDim2.new(0, 200, 0, 50)
Salt.Font = Enum.Font.SourceSans
Salt.Text = "Salt"
Salt.TextColor3 = Color3.fromRGB(255, 255, 255)
Salt.TextSize = 40.000

Limestone.Name = "Limestone"
Limestone.Parent = BallMaterialSelect
Limestone.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Limestone.BackgroundTransparency = 0.700
Limestone.Size = UDim2.new(0, 200, 0, 50)
Limestone.Font = Enum.Font.SourceSans
Limestone.Text = "Limestone"
Limestone.TextColor3 = Color3.fromRGB(255, 255, 255)
Limestone.TextSize = 40.000

Pavement.Name = "Pavement"
Pavement.Parent = BallMaterialSelect
Pavement.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pavement.BackgroundTransparency = 0.700
Pavement.Size = UDim2.new(0, 200, 0, 50)
Pavement.Font = Enum.Font.SourceSans
Pavement.Text = "Pavement"
Pavement.TextColor3 = Color3.fromRGB(255, 255, 255)
Pavement.TextSize = 40.000

ForceField.Name = "ForceField"
ForceField.Parent = BallMaterialSelect
ForceField.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
ForceField.BackgroundTransparency = 0.700
ForceField.Size = UDim2.new(0, 200, 0, 50)
ForceField.Font = Enum.Font.SourceSans
ForceField.Text = "ForceField"
ForceField.TextColor3 = Color3.fromRGB(255, 255, 255)
ForceField.TextSize = 40.000

Default.Name = "Default"
Default.Parent = BallMaterialSelect
Default.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Default.BackgroundTransparency = 0.700
Default.Size = UDim2.new(0, 200, 0, 50)
Default.Font = Enum.Font.SourceSans
Default.Text = "Default"
Default.TextColor3 = Color3.fromRGB(255, 255, 255)
Default.TextSize = 40.000

AxeMaterialSelect.Name = "Axe Material Select"
AxeMaterialSelect.Parent = CosmeticsBAA
AxeMaterialSelect.Active = true
AxeMaterialSelect.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
AxeMaterialSelect.BackgroundTransparency = 0.650
AxeMaterialSelect.Position = UDim2.new(0.417974383, 0, 0.311627924, 0)
AxeMaterialSelect.Size = UDim2.new(0, 229, 0, 243)
AxeMaterialSelect.Visible = false
AxeMaterialSelect.CanvasPosition = Vector2.new(0, 1787)
AxeMaterialSelect.CanvasSize = UDim2.new(0, 0, 0, 0)

Plastic_2.Name = "Plastic"
Plastic_2.Parent = AxeMaterialSelect
Plastic_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Plastic_2.BackgroundTransparency = 0.700
Plastic_2.Size = UDim2.new(0, 200, 0, 50)
Plastic_2.Font = Enum.Font.SourceSans
Plastic_2.Text = "Plastic"
Plastic_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Plastic_2.TextSize = 40.000

Wood_2.Name = "Wood"
Wood_2.Parent = AxeMaterialSelect
Wood_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Wood_2.BackgroundTransparency = 0.700
Wood_2.Size = UDim2.new(0, 200, 0, 50)
Wood_2.Font = Enum.Font.SourceSans
Wood_2.Text = "Wood"
Wood_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Wood_2.TextSize = 40.000

Slate_2.Name = "Slate"
Slate_2.Parent = AxeMaterialSelect
Slate_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Slate_2.BackgroundTransparency = 0.700
Slate_2.Size = UDim2.new(0, 200, 0, 50)
Slate_2.Font = Enum.Font.SourceSans
Slate_2.Text = "Slate"
Slate_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Slate_2.TextSize = 40.000

Concrete_2.Name = "Concrete"
Concrete_2.Parent = AxeMaterialSelect
Concrete_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Concrete_2.BackgroundTransparency = 0.700
Concrete_2.Size = UDim2.new(0, 200, 0, 50)
Concrete_2.Font = Enum.Font.SourceSans
Concrete_2.Text = "ConCrete"
Concrete_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Concrete_2.TextSize = 40.000

UIGridLayout_2.Parent = AxeMaterialSelect
UIGridLayout_2.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIGridLayout_2.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout_2.CellPadding = UDim2.new(0, 0, 0, 5)
UIGridLayout_2.CellSize = UDim2.new(0, 200, 0, 50)

CorrodedMetal_2.Name = "CorrodedMetal"
CorrodedMetal_2.Parent = AxeMaterialSelect
CorrodedMetal_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
CorrodedMetal_2.BackgroundTransparency = 0.700
CorrodedMetal_2.Size = UDim2.new(0, 200, 0, 50)
CorrodedMetal_2.Font = Enum.Font.SourceSans
CorrodedMetal_2.Text = "CorrodedMetal"
CorrodedMetal_2.TextColor3 = Color3.fromRGB(255, 255, 255)
CorrodedMetal_2.TextSize = 40.000

DiamondPlate_2.Name = "DiamondPlate"
DiamondPlate_2.Parent = AxeMaterialSelect
DiamondPlate_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
DiamondPlate_2.BackgroundTransparency = 0.700
DiamondPlate_2.Size = UDim2.new(0, 200, 0, 50)
DiamondPlate_2.Font = Enum.Font.SourceSans
DiamondPlate_2.Text = "DiamondPlate"
DiamondPlate_2.TextColor3 = Color3.fromRGB(255, 255, 255)
DiamondPlate_2.TextSize = 40.000

Foil_2.Name = "Foil"
Foil_2.Parent = AxeMaterialSelect
Foil_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Foil_2.BackgroundTransparency = 0.700
Foil_2.Size = UDim2.new(0, 200, 0, 50)
Foil_2.Font = Enum.Font.SourceSans
Foil_2.Text = "Foil"
Foil_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Foil_2.TextSize = 40.000

Grass_2.Name = "Grass"
Grass_2.Parent = AxeMaterialSelect
Grass_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Grass_2.BackgroundTransparency = 0.700
Grass_2.Size = UDim2.new(0, 200, 0, 50)
Grass_2.Font = Enum.Font.SourceSans
Grass_2.Text = "Grass"
Grass_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Grass_2.TextSize = 40.000

Ice_2.Name = "Ice"
Ice_2.Parent = AxeMaterialSelect
Ice_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ice_2.BackgroundTransparency = 0.700
Ice_2.Size = UDim2.new(0, 200, 0, 50)
Ice_2.Font = Enum.Font.SourceSans
Ice_2.Text = "Ice"
Ice_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Ice_2.TextSize = 40.000

Marble_2.Name = "Marble"
Marble_2.Parent = AxeMaterialSelect
Marble_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Marble_2.BackgroundTransparency = 0.700
Marble_2.Size = UDim2.new(0, 200, 0, 50)
Marble_2.Font = Enum.Font.SourceSans
Marble_2.Text = "Marble"
Marble_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Marble_2.TextSize = 40.000

Granite_2.Name = "Granite"
Granite_2.Parent = AxeMaterialSelect
Granite_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Granite_2.BackgroundTransparency = 0.700
Granite_2.Size = UDim2.new(0, 200, 0, 50)
Granite_2.Font = Enum.Font.SourceSans
Granite_2.Text = "Granite"
Granite_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Granite_2.TextSize = 40.000

Brick_2.Name = "Brick"
Brick_2.Parent = AxeMaterialSelect
Brick_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Brick_2.BackgroundTransparency = 0.700
Brick_2.Size = UDim2.new(0, 200, 0, 50)
Brick_2.Font = Enum.Font.SourceSans
Brick_2.Text = "Brick"
Brick_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Brick_2.TextSize = 40.000

Pebble_2.Name = "Pebble"
Pebble_2.Parent = AxeMaterialSelect
Pebble_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pebble_2.BackgroundTransparency = 0.700
Pebble_2.Size = UDim2.new(0, 200, 0, 50)
Pebble_2.Font = Enum.Font.SourceSans
Pebble_2.Text = "Pebble"
Pebble_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Pebble_2.TextSize = 40.000

Sand_2.Name = "Sand"
Sand_2.Parent = AxeMaterialSelect
Sand_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Sand_2.BackgroundTransparency = 0.700
Sand_2.Size = UDim2.new(0, 200, 0, 50)
Sand_2.Font = Enum.Font.SourceSans
Sand_2.Text = "Sand"
Sand_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Sand_2.TextSize = 40.000

Fabric_2.Name = "Fabric"
Fabric_2.Parent = AxeMaterialSelect
Fabric_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Fabric_2.BackgroundTransparency = 0.700
Fabric_2.Size = UDim2.new(0, 200, 0, 50)
Fabric_2.Font = Enum.Font.SourceSans
Fabric_2.Text = "Fabric"
Fabric_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Fabric_2.TextSize = 40.000

SmoothPlastic_2.Name = "SmoothPlastic"
SmoothPlastic_2.Parent = AxeMaterialSelect
SmoothPlastic_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
SmoothPlastic_2.BackgroundTransparency = 0.700
SmoothPlastic_2.Size = UDim2.new(0, 200, 0, 50)
SmoothPlastic_2.Font = Enum.Font.SourceSans
SmoothPlastic_2.Text = "SmoothPlastic"
SmoothPlastic_2.TextColor3 = Color3.fromRGB(255, 255, 255)
SmoothPlastic_2.TextSize = 40.000

Metal_2.Name = "Metal"
Metal_2.Parent = AxeMaterialSelect
Metal_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Metal_2.BackgroundTransparency = 0.700
Metal_2.Size = UDim2.new(0, 200, 0, 50)
Metal_2.Font = Enum.Font.SourceSans
Metal_2.Text = "Metal"
Metal_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Metal_2.TextSize = 40.000

WoodPlanks_2.Name = "WoodPlanks"
WoodPlanks_2.Parent = AxeMaterialSelect
WoodPlanks_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
WoodPlanks_2.BackgroundTransparency = 0.700
WoodPlanks_2.Size = UDim2.new(0, 200, 0, 50)
WoodPlanks_2.Font = Enum.Font.SourceSans
WoodPlanks_2.Text = "WoodPlanks"
WoodPlanks_2.TextColor3 = Color3.fromRGB(255, 255, 255)
WoodPlanks_2.TextSize = 40.000

Cobblestone_2.Name = "Cobblestone"
Cobblestone_2.Parent = AxeMaterialSelect
Cobblestone_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Cobblestone_2.BackgroundTransparency = 0.700
Cobblestone_2.Size = UDim2.new(0, 200, 0, 50)
Cobblestone_2.Font = Enum.Font.SourceSans
Cobblestone_2.Text = "Cobblestone"
Cobblestone_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Cobblestone_2.TextSize = 40.000

Air_2.Name = "Air"
Air_2.Parent = AxeMaterialSelect
Air_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Air_2.BackgroundTransparency = 0.700
Air_2.Size = UDim2.new(0, 200, 0, 50)
Air_2.Font = Enum.Font.SourceSans
Air_2.Text = "Air"
Air_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Air_2.TextSize = 40.000

Water_2.Name = "Water"
Water_2.Parent = AxeMaterialSelect
Water_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Water_2.BackgroundTransparency = 0.700
Water_2.Size = UDim2.new(0, 200, 0, 50)
Water_2.Font = Enum.Font.SourceSans
Water_2.Text = "Water"
Water_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Water_2.TextSize = 40.000

Rock_2.Name = "Rock"
Rock_2.Parent = AxeMaterialSelect
Rock_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Rock_2.BackgroundTransparency = 0.700
Rock_2.Size = UDim2.new(0, 200, 0, 50)
Rock_2.Font = Enum.Font.SourceSans
Rock_2.Text = "Rock"
Rock_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Rock_2.TextSize = 40.000

Glacier_2.Name = "Glacier"
Glacier_2.Parent = AxeMaterialSelect
Glacier_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Glacier_2.BackgroundTransparency = 0.700
Glacier_2.Size = UDim2.new(0, 200, 0, 50)
Glacier_2.Font = Enum.Font.SourceSans
Glacier_2.Text = "Glacier"
Glacier_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Glacier_2.TextSize = 40.000

Snow_2.Name = "Snow"
Snow_2.Parent = AxeMaterialSelect
Snow_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Snow_2.BackgroundTransparency = 0.700
Snow_2.Size = UDim2.new(0, 200, 0, 50)
Snow_2.Font = Enum.Font.SourceSans
Snow_2.Text = "Snow"
Snow_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Snow_2.TextSize = 40.000

Sandstone_2.Name = "Sandstone"
Sandstone_2.Parent = AxeMaterialSelect
Sandstone_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Sandstone_2.BackgroundTransparency = 0.700
Sandstone_2.Size = UDim2.new(0, 200, 0, 50)
Sandstone_2.Font = Enum.Font.SourceSans
Sandstone_2.Text = "Sandstone"
Sandstone_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Sandstone_2.TextSize = 40.000

Mud_2.Name = "Mud"
Mud_2.Parent = AxeMaterialSelect
Mud_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Mud_2.BackgroundTransparency = 0.700
Mud_2.Size = UDim2.new(0, 200, 0, 50)
Mud_2.Font = Enum.Font.SourceSans
Mud_2.Text = "Mud"
Mud_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Mud_2.TextSize = 40.000

Basalt_2.Name = "Basalt"
Basalt_2.Parent = AxeMaterialSelect
Basalt_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Basalt_2.BackgroundTransparency = 0.700
Basalt_2.Size = UDim2.new(0, 200, 0, 50)
Basalt_2.Font = Enum.Font.SourceSans
Basalt_2.Text = "Basalt"
Basalt_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Basalt_2.TextSize = 40.000

Ground_2.Name = "Ground"
Ground_2.Parent = AxeMaterialSelect
Ground_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ground_2.BackgroundTransparency = 0.700
Ground_2.Size = UDim2.new(0, 200, 0, 50)
Ground_2.Font = Enum.Font.SourceSans
Ground_2.Text = "Ground"
Ground_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Ground_2.TextSize = 40.000

CrackedLava_2.Name = "CrackedLava"
CrackedLava_2.Parent = AxeMaterialSelect
CrackedLava_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
CrackedLava_2.BackgroundTransparency = 0.700
CrackedLava_2.Size = UDim2.new(0, 200, 0, 50)
CrackedLava_2.Font = Enum.Font.SourceSans
CrackedLava_2.Text = "CrackedLava"
CrackedLava_2.TextColor3 = Color3.fromRGB(255, 255, 255)
CrackedLava_2.TextSize = 40.000

Neon_2.Name = "Neon"
Neon_2.Parent = AxeMaterialSelect
Neon_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Neon_2.BackgroundTransparency = 0.700
Neon_2.Size = UDim2.new(0, 200, 0, 50)
Neon_2.Font = Enum.Font.SourceSans
Neon_2.Text = "Neon"
Neon_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Neon_2.TextSize = 40.000

Glass_2.Name = "Glass"
Glass_2.Parent = AxeMaterialSelect
Glass_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Glass_2.BackgroundTransparency = 0.700
Glass_2.Size = UDim2.new(0, 200, 0, 50)
Glass_2.Font = Enum.Font.SourceSans
Glass_2.Text = "Glass"
Glass_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Glass_2.TextSize = 40.000

Asphalt_2.Name = "Asphalt"
Asphalt_2.Parent = AxeMaterialSelect
Asphalt_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Asphalt_2.BackgroundTransparency = 0.700
Asphalt_2.Size = UDim2.new(0, 200, 0, 50)
Asphalt_2.Font = Enum.Font.SourceSans
Asphalt_2.Text = "Asphalt"
Asphalt_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Asphalt_2.TextSize = 40.000

LeafyGrass_2.Name = "LeafyGrass"
LeafyGrass_2.Parent = AxeMaterialSelect
LeafyGrass_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
LeafyGrass_2.BackgroundTransparency = 0.700
LeafyGrass_2.Size = UDim2.new(0, 200, 0, 50)
LeafyGrass_2.Font = Enum.Font.SourceSans
LeafyGrass_2.Text = "LeafyGrass"
LeafyGrass_2.TextColor3 = Color3.fromRGB(255, 255, 255)
LeafyGrass_2.TextSize = 40.000

Salt_2.Name = "Salt"
Salt_2.Parent = AxeMaterialSelect
Salt_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Salt_2.BackgroundTransparency = 0.700
Salt_2.Size = UDim2.new(0, 200, 0, 50)
Salt_2.Font = Enum.Font.SourceSans
Salt_2.Text = "Salt"
Salt_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Salt_2.TextSize = 40.000

Limestone_2.Name = "Limestone"
Limestone_2.Parent = AxeMaterialSelect
Limestone_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Limestone_2.BackgroundTransparency = 0.700
Limestone_2.Size = UDim2.new(0, 200, 0, 50)
Limestone_2.Font = Enum.Font.SourceSans
Limestone_2.Text = "Limestone"
Limestone_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Limestone_2.TextSize = 40.000

Pavement_2.Name = "Pavement"
Pavement_2.Parent = AxeMaterialSelect
Pavement_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pavement_2.BackgroundTransparency = 0.700
Pavement_2.Size = UDim2.new(0, 200, 0, 50)
Pavement_2.Font = Enum.Font.SourceSans
Pavement_2.Text = "Pavement"
Pavement_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Pavement_2.TextSize = 40.000

ForceField_2.Name = "ForceField"
ForceField_2.Parent = AxeMaterialSelect
ForceField_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
ForceField_2.BackgroundTransparency = 0.700
ForceField_2.Size = UDim2.new(0, 200, 0, 50)
ForceField_2.Font = Enum.Font.SourceSans
ForceField_2.Text = "ForceField"
ForceField_2.TextColor3 = Color3.fromRGB(255, 255, 255)
ForceField_2.TextSize = 40.000

Default_2.Name = "Default"
Default_2.Parent = AxeMaterialSelect
Default_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Default_2.BackgroundTransparency = 0.700
Default_2.Size = UDim2.new(0, 200, 0, 50)
Default_2.Font = Enum.Font.SourceSans
Default_2.Text = "Default"
Default_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Default_2.TextSize = 40.000

AxeHandleMaterialSelect.Name = "Axe Handle Material Select"
AxeHandleMaterialSelect.Parent = CosmeticsBAA
AxeHandleMaterialSelect.Active = true
AxeHandleMaterialSelect.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
AxeHandleMaterialSelect.BackgroundTransparency = 0.650
AxeHandleMaterialSelect.Position = UDim2.new(0.417974383, 0, 0.311627924, 0)
AxeHandleMaterialSelect.Size = UDim2.new(0, 229, 0, 243)
AxeHandleMaterialSelect.Visible = false
AxeHandleMaterialSelect.CanvasSize = UDim2.new(0, 0, 0, 0)

Plastic_3.Name = "Plastic"
Plastic_3.Parent = AxeHandleMaterialSelect
Plastic_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Plastic_3.BackgroundTransparency = 0.700
Plastic_3.Size = UDim2.new(0, 200, 0, 50)
Plastic_3.Font = Enum.Font.SourceSans
Plastic_3.Text = "Plastic"
Plastic_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Plastic_3.TextSize = 40.000

Wood_3.Name = "Wood"
Wood_3.Parent = AxeHandleMaterialSelect
Wood_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Wood_3.BackgroundTransparency = 0.700
Wood_3.Size = UDim2.new(0, 200, 0, 50)
Wood_3.Font = Enum.Font.SourceSans
Wood_3.Text = "Wood"
Wood_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Wood_3.TextSize = 40.000

Slate_3.Name = "Slate"
Slate_3.Parent = AxeHandleMaterialSelect
Slate_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Slate_3.BackgroundTransparency = 0.700
Slate_3.Size = UDim2.new(0, 200, 0, 50)
Slate_3.Font = Enum.Font.SourceSans
Slate_3.Text = "Slate"
Slate_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Slate_3.TextSize = 40.000

Concrete_3.Name = "Concrete"
Concrete_3.Parent = AxeHandleMaterialSelect
Concrete_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Concrete_3.BackgroundTransparency = 0.700
Concrete_3.Size = UDim2.new(0, 200, 0, 50)
Concrete_3.Font = Enum.Font.SourceSans
Concrete_3.Text = "ConCrete"
Concrete_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Concrete_3.TextSize = 40.000

UIGridLayout_3.Parent = AxeHandleMaterialSelect
UIGridLayout_3.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIGridLayout_3.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout_3.CellPadding = UDim2.new(0, 0, 0, 5)
UIGridLayout_3.CellSize = UDim2.new(0, 200, 0, 50)

CorrodedMetal_3.Name = "CorrodedMetal"
CorrodedMetal_3.Parent = AxeHandleMaterialSelect
CorrodedMetal_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
CorrodedMetal_3.BackgroundTransparency = 0.700
CorrodedMetal_3.Size = UDim2.new(0, 200, 0, 50)
CorrodedMetal_3.Font = Enum.Font.SourceSans
CorrodedMetal_3.Text = "CorrodedMetal"
CorrodedMetal_3.TextColor3 = Color3.fromRGB(255, 255, 255)
CorrodedMetal_3.TextSize = 40.000

DiamondPlate_3.Name = "DiamondPlate"
DiamondPlate_3.Parent = AxeHandleMaterialSelect
DiamondPlate_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
DiamondPlate_3.BackgroundTransparency = 0.700
DiamondPlate_3.Size = UDim2.new(0, 200, 0, 50)
DiamondPlate_3.Font = Enum.Font.SourceSans
DiamondPlate_3.Text = "DiamondPlate"
DiamondPlate_3.TextColor3 = Color3.fromRGB(255, 255, 255)
DiamondPlate_3.TextSize = 40.000

Foil_3.Name = "Foil"
Foil_3.Parent = AxeHandleMaterialSelect
Foil_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Foil_3.BackgroundTransparency = 0.700
Foil_3.Size = UDim2.new(0, 200, 0, 50)
Foil_3.Font = Enum.Font.SourceSans
Foil_3.Text = "Foil"
Foil_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Foil_3.TextSize = 40.000

Grass_3.Name = "Grass"
Grass_3.Parent = AxeHandleMaterialSelect
Grass_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Grass_3.BackgroundTransparency = 0.700
Grass_3.Size = UDim2.new(0, 200, 0, 50)
Grass_3.Font = Enum.Font.SourceSans
Grass_3.Text = "Grass"
Grass_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Grass_3.TextSize = 40.000

Ice_3.Name = "Ice"
Ice_3.Parent = AxeHandleMaterialSelect
Ice_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ice_3.BackgroundTransparency = 0.700
Ice_3.Size = UDim2.new(0, 200, 0, 50)
Ice_3.Font = Enum.Font.SourceSans
Ice_3.Text = "Ice"
Ice_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Ice_3.TextSize = 40.000

Marble_3.Name = "Marble"
Marble_3.Parent = AxeHandleMaterialSelect
Marble_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Marble_3.BackgroundTransparency = 0.700
Marble_3.Size = UDim2.new(0, 200, 0, 50)
Marble_3.Font = Enum.Font.SourceSans
Marble_3.Text = "Marble"
Marble_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Marble_3.TextSize = 40.000

Granite_3.Name = "Granite"
Granite_3.Parent = AxeHandleMaterialSelect
Granite_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Granite_3.BackgroundTransparency = 0.700
Granite_3.Size = UDim2.new(0, 200, 0, 50)
Granite_3.Font = Enum.Font.SourceSans
Granite_3.Text = "Granite"
Granite_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Granite_3.TextSize = 40.000

Brick_3.Name = "Brick"
Brick_3.Parent = AxeHandleMaterialSelect
Brick_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Brick_3.BackgroundTransparency = 0.700
Brick_3.Size = UDim2.new(0, 200, 0, 50)
Brick_3.Font = Enum.Font.SourceSans
Brick_3.Text = "Brick"
Brick_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Brick_3.TextSize = 40.000

Pebble_3.Name = "Pebble"
Pebble_3.Parent = AxeHandleMaterialSelect
Pebble_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pebble_3.BackgroundTransparency = 0.700
Pebble_3.Size = UDim2.new(0, 200, 0, 50)
Pebble_3.Font = Enum.Font.SourceSans
Pebble_3.Text = "Pebble"
Pebble_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Pebble_3.TextSize = 40.000

Sand_3.Name = "Sand"
Sand_3.Parent = AxeHandleMaterialSelect
Sand_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Sand_3.BackgroundTransparency = 0.700
Sand_3.Size = UDim2.new(0, 200, 0, 50)
Sand_3.Font = Enum.Font.SourceSans
Sand_3.Text = "Sand"
Sand_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Sand_3.TextSize = 40.000

Fabric_3.Name = "Fabric"
Fabric_3.Parent = AxeHandleMaterialSelect
Fabric_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Fabric_3.BackgroundTransparency = 0.700
Fabric_3.Size = UDim2.new(0, 200, 0, 50)
Fabric_3.Font = Enum.Font.SourceSans
Fabric_3.Text = "Fabric"
Fabric_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Fabric_3.TextSize = 40.000

SmoothPlastic_3.Name = "SmoothPlastic"
SmoothPlastic_3.Parent = AxeHandleMaterialSelect
SmoothPlastic_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
SmoothPlastic_3.BackgroundTransparency = 0.700
SmoothPlastic_3.Size = UDim2.new(0, 200, 0, 50)
SmoothPlastic_3.Font = Enum.Font.SourceSans
SmoothPlastic_3.Text = "SmoothPlastic"
SmoothPlastic_3.TextColor3 = Color3.fromRGB(255, 255, 255)
SmoothPlastic_3.TextSize = 40.000

Metal_3.Name = "Metal"
Metal_3.Parent = AxeHandleMaterialSelect
Metal_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Metal_3.BackgroundTransparency = 0.700
Metal_3.Size = UDim2.new(0, 200, 0, 50)
Metal_3.Font = Enum.Font.SourceSans
Metal_3.Text = "Metal"
Metal_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Metal_3.TextSize = 40.000

WoodPlanks_3.Name = "WoodPlanks"
WoodPlanks_3.Parent = AxeHandleMaterialSelect
WoodPlanks_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
WoodPlanks_3.BackgroundTransparency = 0.700
WoodPlanks_3.Size = UDim2.new(0, 200, 0, 50)
WoodPlanks_3.Font = Enum.Font.SourceSans
WoodPlanks_3.Text = "WoodPlanks"
WoodPlanks_3.TextColor3 = Color3.fromRGB(255, 255, 255)
WoodPlanks_3.TextSize = 40.000

Cobblestone_3.Name = "Cobblestone"
Cobblestone_3.Parent = AxeHandleMaterialSelect
Cobblestone_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Cobblestone_3.BackgroundTransparency = 0.700
Cobblestone_3.Size = UDim2.new(0, 200, 0, 50)
Cobblestone_3.Font = Enum.Font.SourceSans
Cobblestone_3.Text = "Cobblestone"
Cobblestone_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Cobblestone_3.TextSize = 40.000

Air_3.Name = "Air"
Air_3.Parent = AxeHandleMaterialSelect
Air_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Air_3.BackgroundTransparency = 0.700
Air_3.Size = UDim2.new(0, 200, 0, 50)
Air_3.Font = Enum.Font.SourceSans
Air_3.Text = "Air"
Air_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Air_3.TextSize = 40.000

Water_3.Name = "Water"
Water_3.Parent = AxeHandleMaterialSelect
Water_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Water_3.BackgroundTransparency = 0.700
Water_3.Size = UDim2.new(0, 200, 0, 50)
Water_3.Font = Enum.Font.SourceSans
Water_3.Text = "Water"
Water_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Water_3.TextSize = 40.000

Rock_3.Name = "Rock"
Rock_3.Parent = AxeHandleMaterialSelect
Rock_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Rock_3.BackgroundTransparency = 0.700
Rock_3.Size = UDim2.new(0, 200, 0, 50)
Rock_3.Font = Enum.Font.SourceSans
Rock_3.Text = "Rock"
Rock_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Rock_3.TextSize = 40.000

Glacier_3.Name = "Glacier"
Glacier_3.Parent = AxeHandleMaterialSelect
Glacier_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Glacier_3.BackgroundTransparency = 0.700
Glacier_3.Size = UDim2.new(0, 200, 0, 50)
Glacier_3.Font = Enum.Font.SourceSans
Glacier_3.Text = "Glacier"
Glacier_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Glacier_3.TextSize = 40.000

Snow_3.Name = "Snow"
Snow_3.Parent = AxeHandleMaterialSelect
Snow_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Snow_3.BackgroundTransparency = 0.700
Snow_3.Size = UDim2.new(0, 200, 0, 50)
Snow_3.Font = Enum.Font.SourceSans
Snow_3.Text = "Snow"
Snow_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Snow_3.TextSize = 40.000

Sandstone_3.Name = "Sandstone"
Sandstone_3.Parent = AxeHandleMaterialSelect
Sandstone_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Sandstone_3.BackgroundTransparency = 0.700
Sandstone_3.Size = UDim2.new(0, 200, 0, 50)
Sandstone_3.Font = Enum.Font.SourceSans
Sandstone_3.Text = "Sandstone"
Sandstone_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Sandstone_3.TextSize = 40.000

Mud_3.Name = "Mud"
Mud_3.Parent = AxeHandleMaterialSelect
Mud_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Mud_3.BackgroundTransparency = 0.700
Mud_3.Size = UDim2.new(0, 200, 0, 50)
Mud_3.Font = Enum.Font.SourceSans
Mud_3.Text = "Mud"
Mud_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Mud_3.TextSize = 40.000

Basalt_3.Name = "Basalt"
Basalt_3.Parent = AxeHandleMaterialSelect
Basalt_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Basalt_3.BackgroundTransparency = 0.700
Basalt_3.Size = UDim2.new(0, 200, 0, 50)
Basalt_3.Font = Enum.Font.SourceSans
Basalt_3.Text = "Basalt"
Basalt_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Basalt_3.TextSize = 40.000

Ground_3.Name = "Ground"
Ground_3.Parent = AxeHandleMaterialSelect
Ground_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Ground_3.BackgroundTransparency = 0.700
Ground_3.Size = UDim2.new(0, 200, 0, 50)
Ground_3.Font = Enum.Font.SourceSans
Ground_3.Text = "Ground"
Ground_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Ground_3.TextSize = 40.000

CrackedLava_3.Name = "CrackedLava"
CrackedLava_3.Parent = AxeHandleMaterialSelect
CrackedLava_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
CrackedLava_3.BackgroundTransparency = 0.700
CrackedLava_3.Size = UDim2.new(0, 200, 0, 50)
CrackedLava_3.Font = Enum.Font.SourceSans
CrackedLava_3.Text = "CrackedLava"
CrackedLava_3.TextColor3 = Color3.fromRGB(255, 255, 255)
CrackedLava_3.TextSize = 40.000

Neon_3.Name = "Neon"
Neon_3.Parent = AxeHandleMaterialSelect
Neon_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Neon_3.BackgroundTransparency = 0.700
Neon_3.Size = UDim2.new(0, 200, 0, 50)
Neon_3.Font = Enum.Font.SourceSans
Neon_3.Text = "Neon"
Neon_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Neon_3.TextSize = 40.000

Glass_3.Name = "Glass"
Glass_3.Parent = AxeHandleMaterialSelect
Glass_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Glass_3.BackgroundTransparency = 0.700
Glass_3.Size = UDim2.new(0, 200, 0, 50)
Glass_3.Font = Enum.Font.SourceSans
Glass_3.Text = "Glass"
Glass_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Glass_3.TextSize = 40.000

Asphalt_3.Name = "Asphalt"
Asphalt_3.Parent = AxeHandleMaterialSelect
Asphalt_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Asphalt_3.BackgroundTransparency = 0.700
Asphalt_3.Size = UDim2.new(0, 200, 0, 50)
Asphalt_3.Font = Enum.Font.SourceSans
Asphalt_3.Text = "Asphalt"
Asphalt_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Asphalt_3.TextSize = 40.000

LeafyGrass_3.Name = "LeafyGrass"
LeafyGrass_3.Parent = AxeHandleMaterialSelect
LeafyGrass_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
LeafyGrass_3.BackgroundTransparency = 0.700
LeafyGrass_3.Size = UDim2.new(0, 200, 0, 50)
LeafyGrass_3.Font = Enum.Font.SourceSans
LeafyGrass_3.Text = "LeafyGrass"
LeafyGrass_3.TextColor3 = Color3.fromRGB(255, 255, 255)
LeafyGrass_3.TextSize = 40.000

Salt_3.Name = "Salt"
Salt_3.Parent = AxeHandleMaterialSelect
Salt_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Salt_3.BackgroundTransparency = 0.700
Salt_3.Size = UDim2.new(0, 200, 0, 50)
Salt_3.Font = Enum.Font.SourceSans
Salt_3.Text = "Salt"
Salt_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Salt_3.TextSize = 40.000

Limestone_3.Name = "Limestone"
Limestone_3.Parent = AxeHandleMaterialSelect
Limestone_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Limestone_3.BackgroundTransparency = 0.700
Limestone_3.Size = UDim2.new(0, 200, 0, 50)
Limestone_3.Font = Enum.Font.SourceSans
Limestone_3.Text = "Limestone"
Limestone_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Limestone_3.TextSize = 40.000

Pavement_3.Name = "Pavement"
Pavement_3.Parent = AxeHandleMaterialSelect
Pavement_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pavement_3.BackgroundTransparency = 0.700
Pavement_3.Size = UDim2.new(0, 200, 0, 50)
Pavement_3.Font = Enum.Font.SourceSans
Pavement_3.Text = "Pavement"
Pavement_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Pavement_3.TextSize = 40.000

ForceField_3.Name = "ForceField"
ForceField_3.Parent = AxeHandleMaterialSelect
ForceField_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
ForceField_3.BackgroundTransparency = 0.700
ForceField_3.Size = UDim2.new(0, 200, 0, 50)
ForceField_3.Font = Enum.Font.SourceSans
ForceField_3.Text = "ForceField"
ForceField_3.TextColor3 = Color3.fromRGB(255, 255, 255)
ForceField_3.TextSize = 40.000

Default_3.Name = "Default"
Default_3.Parent = AxeHandleMaterialSelect
Default_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Default_3.BackgroundTransparency = 0.700
Default_3.Size = UDim2.new(0, 200, 0, 50)
Default_3.Font = Enum.Font.SourceSans
Default_3.Text = "Default"
Default_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Default_3.TextSize = 40.000

BallColorSelect.Name = "Ball Color Select"
BallColorSelect.Parent = CosmeticsBAA
BallColorSelect.Active = true
BallColorSelect.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
BallColorSelect.BackgroundTransparency = 0.650
BallColorSelect.Position = UDim2.new(0.417974383, 0, 0.311627924, 0)
BallColorSelect.Size = UDim2.new(0, 229, 0, 243)
BallColorSelect.Visible = false
BallColorSelect.CanvasPosition = Vector2.new(0, 167)
BallColorSelect.CanvasSize = UDim2.new(0, 0, 0, 0)

UIGridLayout_4.Parent = BallColorSelect
UIGridLayout_4.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIGridLayout_4.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout_4.CellPadding = UDim2.new(0, 0, 0, 5)
UIGridLayout_4.CellSize = UDim2.new(0, 200, 0, 50)

White.Name = "White"
White.Parent = BallColorSelect
White.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
White.BackgroundTransparency = 0.700
White.Size = UDim2.new(0, 200, 0, 50)
White.Font = Enum.Font.SourceSans
White.Text = "White"
White.TextColor3 = Color3.fromRGB(255, 255, 255)
White.TextSize = 40.000

Red.Name = "Red"
Red.Parent = BallColorSelect
Red.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Red.BackgroundTransparency = 0.700
Red.Size = UDim2.new(0, 200, 0, 50)
Red.Font = Enum.Font.SourceSans
Red.Text = "Red"
Red.TextColor3 = Color3.fromRGB(255, 255, 255)
Red.TextSize = 40.000

Crimson.Name = "Crimson"
Crimson.Parent = BallColorSelect
Crimson.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Crimson.BackgroundTransparency = 0.700
Crimson.Size = UDim2.new(0, 200, 0, 50)
Crimson.Font = Enum.Font.SourceSans
Crimson.Text = "Crimson"
Crimson.TextColor3 = Color3.fromRGB(255, 255, 255)
Crimson.TextSize = 40.000

Cyan.Name = "Cyan"
Cyan.Parent = BallColorSelect
Cyan.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Cyan.BackgroundTransparency = 0.700
Cyan.Size = UDim2.new(0, 200, 0, 50)
Cyan.Font = Enum.Font.SourceSans
Cyan.Text = "Cyan"
Cyan.TextColor3 = Color3.fromRGB(255, 255, 255)
Cyan.TextSize = 40.000

Yellow.Name = "Yellow"
Yellow.Parent = BallColorSelect
Yellow.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Yellow.BackgroundTransparency = 0.700
Yellow.Size = UDim2.new(0, 200, 0, 50)
Yellow.Font = Enum.Font.SourceSans
Yellow.Text = "Yellow"
Yellow.TextColor3 = Color3.fromRGB(255, 255, 255)
Yellow.TextSize = 40.000

Green.Name = "Green"
Green.Parent = BallColorSelect
Green.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Green.BackgroundTransparency = 0.700
Green.Size = UDim2.new(0, 200, 0, 50)
Green.Font = Enum.Font.SourceSans
Green.Text = "Green"
Green.TextColor3 = Color3.fromRGB(255, 255, 255)
Green.TextSize = 40.000

Pink.Name = "Pink"
Pink.Parent = BallColorSelect
Pink.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pink.BackgroundTransparency = 0.700
Pink.Size = UDim2.new(0, 200, 0, 50)
Pink.Font = Enum.Font.SourceSans
Pink.Text = "Pink"
Pink.TextColor3 = Color3.fromRGB(255, 255, 255)
Pink.TextSize = 40.000

Purple.Name = "Purple"
Purple.Parent = BallColorSelect
Purple.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Purple.BackgroundTransparency = 0.700
Purple.Size = UDim2.new(0, 200, 0, 50)
Purple.Font = Enum.Font.SourceSans
Purple.Text = "Purple"
Purple.TextColor3 = Color3.fromRGB(255, 255, 255)
Purple.TextSize = 40.000

Blue.Name = "Blue"
Blue.Parent = BallColorSelect
Blue.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Blue.BackgroundTransparency = 0.700
Blue.Size = UDim2.new(0, 200, 0, 50)
Blue.Font = Enum.Font.SourceSans
Blue.Text = "Blue"
Blue.TextColor3 = Color3.fromRGB(255, 255, 255)
Blue.TextSize = 40.000

Lime.Name = "Lime"
Lime.Parent = BallColorSelect
Lime.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Lime.BackgroundTransparency = 0.700
Lime.Size = UDim2.new(0, 200, 0, 50)
Lime.Font = Enum.Font.SourceSans
Lime.Text = "Lime"
Lime.TextColor3 = Color3.fromRGB(255, 255, 255)
Lime.TextSize = 40.000

Gray.Name = "Gray"
Gray.Parent = BallColorSelect
Gray.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Gray.BackgroundTransparency = 0.700
Gray.Size = UDim2.new(0, 200, 0, 50)
Gray.Font = Enum.Font.SourceSans
Gray.Text = "Gray"
Gray.TextColor3 = Color3.fromRGB(255, 255, 255)
Gray.TextSize = 40.000

Brown.Name = "Brown"
Brown.Parent = BallColorSelect
Brown.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Brown.BackgroundTransparency = 0.700
Brown.Size = UDim2.new(0, 200, 0, 50)
Brown.Font = Enum.Font.SourceSans
Brown.Text = "Brown"
Brown.TextColor3 = Color3.fromRGB(255, 255, 255)
Brown.TextSize = 40.000

Tan.Name = "Tan"
Tan.Parent = BallColorSelect
Tan.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Tan.BackgroundTransparency = 0.700
Tan.Size = UDim2.new(0, 200, 0, 50)
Tan.Font = Enum.Font.SourceSans
Tan.Text = "Tan"
Tan.TextColor3 = Color3.fromRGB(255, 255, 255)
Tan.TextSize = 40.000

AxeHandleColorSelect.Name = "Axe Handle Color Select"
AxeHandleColorSelect.Parent = CosmeticsBAA
AxeHandleColorSelect.Active = true
AxeHandleColorSelect.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
AxeHandleColorSelect.BackgroundTransparency = 0.650
AxeHandleColorSelect.Position = UDim2.new(0.417974383, 0, 0.311627924, 0)
AxeHandleColorSelect.Size = UDim2.new(0, 229, 0, 243)
AxeHandleColorSelect.Visible = false
AxeHandleColorSelect.CanvasSize = UDim2.new(0, 0, 0, 0)

UIGridLayout_5.Parent = AxeHandleColorSelect
UIGridLayout_5.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIGridLayout_5.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout_5.CellPadding = UDim2.new(0, 0, 0, 5)
UIGridLayout_5.CellSize = UDim2.new(0, 200, 0, 50)

White_2.Name = "White"
White_2.Parent = AxeHandleColorSelect
White_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
White_2.BackgroundTransparency = 0.700
White_2.Size = UDim2.new(0, 200, 0, 50)
White_2.Font = Enum.Font.SourceSans
White_2.Text = "White"
White_2.TextColor3 = Color3.fromRGB(255, 255, 255)
White_2.TextSize = 40.000

Red_2.Name = "Red"
Red_2.Parent = AxeHandleColorSelect
Red_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Red_2.BackgroundTransparency = 0.700
Red_2.Size = UDim2.new(0, 200, 0, 50)
Red_2.Font = Enum.Font.SourceSans
Red_2.Text = "Red"
Red_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Red_2.TextSize = 40.000

Crimson_2.Name = "Crimson"
Crimson_2.Parent = AxeHandleColorSelect
Crimson_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Crimson_2.BackgroundTransparency = 0.700
Crimson_2.Size = UDim2.new(0, 200, 0, 50)
Crimson_2.Font = Enum.Font.SourceSans
Crimson_2.Text = "Crimson"
Crimson_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Crimson_2.TextSize = 40.000

Cyan_2.Name = "Cyan"
Cyan_2.Parent = AxeHandleColorSelect
Cyan_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Cyan_2.BackgroundTransparency = 0.700
Cyan_2.Size = UDim2.new(0, 200, 0, 50)
Cyan_2.Font = Enum.Font.SourceSans
Cyan_2.Text = "Cyan"
Cyan_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Cyan_2.TextSize = 40.000

Yellow_2.Name = "Yellow"
Yellow_2.Parent = AxeHandleColorSelect
Yellow_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Yellow_2.BackgroundTransparency = 0.700
Yellow_2.Size = UDim2.new(0, 200, 0, 50)
Yellow_2.Font = Enum.Font.SourceSans
Yellow_2.Text = "Yellow"
Yellow_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Yellow_2.TextSize = 40.000

Green_2.Name = "Green"
Green_2.Parent = AxeHandleColorSelect
Green_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Green_2.BackgroundTransparency = 0.700
Green_2.Size = UDim2.new(0, 200, 0, 50)
Green_2.Font = Enum.Font.SourceSans
Green_2.Text = "Green"
Green_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Green_2.TextSize = 40.000

Pink_2.Name = "Pink"
Pink_2.Parent = AxeHandleColorSelect
Pink_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pink_2.BackgroundTransparency = 0.700
Pink_2.Size = UDim2.new(0, 200, 0, 50)
Pink_2.Font = Enum.Font.SourceSans
Pink_2.Text = "Pink"
Pink_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Pink_2.TextSize = 40.000

Purple_2.Name = "Purple"
Purple_2.Parent = AxeHandleColorSelect
Purple_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Purple_2.BackgroundTransparency = 0.700
Purple_2.Size = UDim2.new(0, 200, 0, 50)
Purple_2.Font = Enum.Font.SourceSans
Purple_2.Text = "Purple"
Purple_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Purple_2.TextSize = 40.000

Blue_2.Name = "Blue"
Blue_2.Parent = AxeHandleColorSelect
Blue_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Blue_2.BackgroundTransparency = 0.700
Blue_2.Size = UDim2.new(0, 200, 0, 50)
Blue_2.Font = Enum.Font.SourceSans
Blue_2.Text = "Blue"
Blue_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Blue_2.TextSize = 40.000

Lime_2.Name = "Lime"
Lime_2.Parent = AxeHandleColorSelect
Lime_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Lime_2.BackgroundTransparency = 0.700
Lime_2.Size = UDim2.new(0, 200, 0, 50)
Lime_2.Font = Enum.Font.SourceSans
Lime_2.Text = "Lime"
Lime_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Lime_2.TextSize = 40.000

Gray_2.Name = "Gray"
Gray_2.Parent = AxeHandleColorSelect
Gray_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Gray_2.BackgroundTransparency = 0.700
Gray_2.Size = UDim2.new(0, 200, 0, 50)
Gray_2.Font = Enum.Font.SourceSans
Gray_2.Text = "Gray"
Gray_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Gray_2.TextSize = 40.000

Brown_2.Name = "Brown"
Brown_2.Parent = AxeHandleColorSelect
Brown_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Brown_2.BackgroundTransparency = 0.700
Brown_2.Size = UDim2.new(0, 200, 0, 50)
Brown_2.Font = Enum.Font.SourceSans
Brown_2.Text = "Brown"
Brown_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Brown_2.TextSize = 40.000

Tan_2.Name = "Tan"
Tan_2.Parent = AxeHandleColorSelect
Tan_2.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Tan_2.BackgroundTransparency = 0.700
Tan_2.Size = UDim2.new(0, 200, 0, 50)
Tan_2.Font = Enum.Font.SourceSans
Tan_2.Text = "Tan"
Tan_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Tan_2.TextSize = 40.000

Default_4.Name = "Default"
Default_4.Parent = AxeHandleColorSelect
Default_4.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Default_4.BackgroundTransparency = 0.700
Default_4.Size = UDim2.new(0, 200, 0, 50)
Default_4.Font = Enum.Font.SourceSans
Default_4.Text = "Default"
Default_4.TextColor3 = Color3.fromRGB(255, 255, 255)
Default_4.TextSize = 40.000

AxeColorSelect.Name = "Axe Color Select"
AxeColorSelect.Parent = CosmeticsBAA
AxeColorSelect.Active = true
AxeColorSelect.BackgroundColor3 = Color3.fromRGB(131, 78, 206)
AxeColorSelect.BackgroundTransparency = 0.650
AxeColorSelect.Position = UDim2.new(0.417974383, 0, 0.311627924, 0)
AxeColorSelect.Size = UDim2.new(0, 229, 0, 243)
AxeColorSelect.Visible = false
AxeColorSelect.CanvasSize = UDim2.new(0, 0, 0, 0)

UIGridLayout_6.Parent = AxeColorSelect
UIGridLayout_6.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIGridLayout_6.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout_6.CellPadding = UDim2.new(0, 0, 0, 5)
UIGridLayout_6.CellSize = UDim2.new(0, 200, 0, 50)

White_3.Name = "White"
White_3.Parent = AxeColorSelect
White_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
White_3.BackgroundTransparency = 0.700
White_3.Size = UDim2.new(0, 200, 0, 50)
White_3.Font = Enum.Font.SourceSans
White_3.Text = "White"
White_3.TextColor3 = Color3.fromRGB(255, 255, 255)
White_3.TextSize = 40.000

Red_3.Name = "Red"
Red_3.Parent = AxeColorSelect
Red_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Red_3.BackgroundTransparency = 0.700
Red_3.Size = UDim2.new(0, 200, 0, 50)
Red_3.Font = Enum.Font.SourceSans
Red_3.Text = "Red"
Red_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Red_3.TextSize = 40.000

Crimson_3.Name = "Crimson"
Crimson_3.Parent = AxeColorSelect
Crimson_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Crimson_3.BackgroundTransparency = 0.700
Crimson_3.Size = UDim2.new(0, 200, 0, 50)
Crimson_3.Font = Enum.Font.SourceSans
Crimson_3.Text = "Crimson"
Crimson_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Crimson_3.TextSize = 40.000

Cyan_3.Name = "Cyan"
Cyan_3.Parent = AxeColorSelect
Cyan_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Cyan_3.BackgroundTransparency = 0.700
Cyan_3.Size = UDim2.new(0, 200, 0, 50)
Cyan_3.Font = Enum.Font.SourceSans
Cyan_3.Text = "Cyan"
Cyan_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Cyan_3.TextSize = 40.000

Yellow_3.Name = "Yellow"
Yellow_3.Parent = AxeColorSelect
Yellow_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Yellow_3.BackgroundTransparency = 0.700
Yellow_3.Size = UDim2.new(0, 200, 0, 50)
Yellow_3.Font = Enum.Font.SourceSans
Yellow_3.Text = "Yellow"
Yellow_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Yellow_3.TextSize = 40.000

Green_3.Name = "Green"
Green_3.Parent = AxeColorSelect
Green_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Green_3.BackgroundTransparency = 0.700
Green_3.Size = UDim2.new(0, 200, 0, 50)
Green_3.Font = Enum.Font.SourceSans
Green_3.Text = "Green"
Green_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Green_3.TextSize = 40.000

Pink_3.Name = "Pink"
Pink_3.Parent = AxeColorSelect
Pink_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Pink_3.BackgroundTransparency = 0.700
Pink_3.Size = UDim2.new(0, 200, 0, 50)
Pink_3.Font = Enum.Font.SourceSans
Pink_3.Text = "Pink"
Pink_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Pink_3.TextSize = 40.000

Purple_3.Name = "Purple"
Purple_3.Parent = AxeColorSelect
Purple_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Purple_3.BackgroundTransparency = 0.700
Purple_3.Size = UDim2.new(0, 200, 0, 50)
Purple_3.Font = Enum.Font.SourceSans
Purple_3.Text = "Purple"
Purple_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Purple_3.TextSize = 40.000

Blue_3.Name = "Blue"
Blue_3.Parent = AxeColorSelect
Blue_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Blue_3.BackgroundTransparency = 0.700
Blue_3.Size = UDim2.new(0, 200, 0, 50)
Blue_3.Font = Enum.Font.SourceSans
Blue_3.Text = "Blue"
Blue_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Blue_3.TextSize = 40.000

Lime_3.Name = "Lime"
Lime_3.Parent = AxeColorSelect
Lime_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Lime_3.BackgroundTransparency = 0.700
Lime_3.Size = UDim2.new(0, 200, 0, 50)
Lime_3.Font = Enum.Font.SourceSans
Lime_3.Text = "Lime"
Lime_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Lime_3.TextSize = 40.000

Gray_3.Name = "Gray"
Gray_3.Parent = AxeColorSelect
Gray_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Gray_3.BackgroundTransparency = 0.700
Gray_3.Size = UDim2.new(0, 200, 0, 50)
Gray_3.Font = Enum.Font.SourceSans
Gray_3.Text = "Gray"
Gray_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Gray_3.TextSize = 40.000

Brown_3.Name = "Brown"
Brown_3.Parent = AxeColorSelect
Brown_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Brown_3.BackgroundTransparency = 0.700
Brown_3.Size = UDim2.new(0, 200, 0, 50)
Brown_3.Font = Enum.Font.SourceSans
Brown_3.Text = "Brown"
Brown_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Brown_3.TextSize = 40.000

Tan_3.Name = "Tan"
Tan_3.Parent = AxeColorSelect
Tan_3.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Tan_3.BackgroundTransparency = 0.700
Tan_3.Size = UDim2.new(0, 200, 0, 50)
Tan_3.Font = Enum.Font.SourceSans
Tan_3.Text = "Tan"
Tan_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Tan_3.TextSize = 40.000

Default_5.Name = "Default"
Default_5.Parent = AxeColorSelect
Default_5.BackgroundColor3 = Color3.fromRGB(1, 39, 255)
Default_5.BackgroundTransparency = 0.700
Default_5.Size = UDim2.new(0, 200, 0, 50)
Default_5.Font = Enum.Font.SourceSans
Default_5.Text = "Default"
Default_5.TextColor3 = Color3.fromRGB(255, 255, 255)
Default_5.TextSize = 40.000

-- Scripts:

local function DKRO_fake_script() -- OC.OpenClose script 
	local script = Instance.new('LocalScript', OC)

	local SP = script.Parent
	local SPP = script.Parent.Parent
	local Toggle = false
	
	SP.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Expand()
	end)
	
	
	function Expand()
		if Toggle then
			SP.Parent.Size = UDim2.new(0, 483, 0, 333)
			SP.Position = UDim2.new(0, 439, 0, 6)
			SP.Text = "<"
			SPP.Logo.Position = UDim2.new(0, 4, 0, 4)
			SPP["Axe Handle"].Visible = true
			SPP["Axe Handle Color"].Visible = true
			SPP["Axe Handle Material"].Visible = true
			SPP.Axe.Visible = true
			SPP["Axe Color"].Visible = true
			SPP["Axe Material"].Visible = true
			SPP.Ball.Visible = true
			SPP["Ball Color"].Visible = true
			SPP["Ball Material"].Visible = true
			
		else
			SP.Parent.Size = UDim2.new(0, 161,0, 111)
			SP.Position = UDim2.new(0, 117, 0, 6)
			SP.Text = ">"
			SPP.Logo.Position = UDim2.new(0, 4, 0, 4)
			SPP["Axe Handle"].Visible = false
			SPP["Axe Handle Color"].Visible = false
			SPP["Axe Handle Material"].Visible = false
			SPP.Axe.Visible = false
			SPP["Axe Color"].Visible = false
			SPP["Axe Material"].Visible = false
			SPP.Ball.Visible = false
			SPP["Ball Color"].Visible = false
			SPP["Ball Material"].Visible = false
		end
	end
	Expand()
end
coroutine.wrap(DKRO_fake_script)()
local function KGBOKW_fake_script() -- CosmeticsMainFrame.Draggable 
	local script = Instance.new('LocalScript', CosmeticsMainFrame)

	script.Parent.Draggable = true
end
coroutine.wrap(KGBOKW_fake_script)()
local function DUYHYT_fake_script() -- AxeHandleMaterial.Axe Handle script 
	local script = Instance.new('LocalScript', AxeHandleMaterial)

	local Material = script.Parent.Parent.Parent["Axe Handle Material Select"]
	local LocalPlayer = game.Players.LocalPlayer.Name
	local Parent = script.Parent
	local handle = game.Workspace.playerModels:WaitForChild(LocalPlayer).axe.handle
	local Toggle = false
	
	
	script.Parent.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Select()
	end)
	
	function Select()
		if Toggle then
			Material.Visible = true
		else
			Material.Visible = false
		end
	end
	
	
	Material.Default.MouseButton1Click:Connect(function()
		handle.Material = "SmoothPlastic"
		Parent.Text = "Material: Default"
		Toggle = false	
		Select()
	end)
	Material.Plastic.MouseButton1Click:Connect(function()
		handle.Material = "Plastic"
		Parent.Text = "Material: Plastic"
		Toggle = false
		Select()
	end)
	Material.Wood.MouseButton1Click:Connect(function()
		handle.Material = "Wood"
		Parent.Text = "Material: Wood"
		Toggle = false
		Select()
	end)
	Material.Slate.MouseButton1Click:Connect(function()
		handle.Material = "Slate"
		Parent.Text = "Material: Slate"
		Toggle = false
		Select()
	end)
	Material.Concrete.MouseButton1Click:Connect(function()
		handle.Material = "Concrete"
		Parent.Text = "Material: Concrete"
		Toggle = false
		Select()
	end)
	Material.CorrodedMetal.MouseButton1Click:Connect(function()
		handle.Material = "CorrodedMetal"
		Parent.Text = "Material: CorrodedMetal"
		Toggle = false
		Select()
	end)
	Material.DiamondPlate.MouseButton1Click:Connect(function()
		handle.Material = "DiamondPlate"
		Parent.Text = "Material: DiamondPlate"
		Toggle = false
		Select()
	end)
	Material.Foil.MouseButton1Click:Connect(function()
		handle.Material = "Foil"
		Parent.Text = "Material: Foil"
		Toggle = false
		Select()
	end)
	Material.Grass.MouseButton1Click:Connect(function()
		handle.Material = "Grass"
		Parent.Text = "Material: Grass"
		Toggle = false
		Select()
	end)
	Material.Ice.MouseButton1Click:Connect(function()
		handle.Material = "Ice"
		Parent.Text = "Material: Ice"
		Toggle = false
		Select()
	end)
	Material.Marble.MouseButton1Click:Connect(function()
		handle.Material = "Marble"
		Parent.Text = "Material: Marble"
		Toggle = false
		Select()
	end)
	Material.Granite.MouseButton1Click:Connect(function()
		handle.Material = "Granite"
		Parent.Text = "Material: Granite"
		Toggle = false
		Select()
	end)
	Material.Brick.MouseButton1Click:Connect(function()
		handle.Material = "Brick"
		Parent.Text = "Material: Brick"
		Toggle = false
		Select()
	end)
	Material.Pebble.MouseButton1Click:Connect(function()
		handle.Material = "Pebble"
		Parent.Text = "Material: Pebble"
		Toggle = false
		Select()
	end)
	Material.Sand.MouseButton1Click:Connect(function()
		handle.Material = "Sand"
		Parent.Text = "Material: Sand"
		Toggle = false
		Select()
	end)
	Material.Fabric.MouseButton1Click:Connect(function()
		handle.Material = "Fabric"
		Parent.Text = "Material: Fabric"
		Toggle = false
		Select()
	end)
	Material.SmoothPlastic.MouseButton1Click:Connect(function()
		handle.Material = "SmoothPlastic"
		Parent.Text = "Material: SmoothPlastic"
		Toggle = false
		Select()
	end)
	Material.Metal.MouseButton1Click:Connect(function()
		handle.Material = "Metal"
		Parent.Text = "Material: Metal"
		Toggle = false
		Select()
	end)
	Material.WoodPlanks.MouseButton1Click:Connect(function()
		handle.Material = "WoodPlanks"
		Parent.Text = "Material: WoodPlanks"
		Toggle = false
		Select()
	end)
	Material.Cobblestone.MouseButton1Click:Connect(function()
		handle.Material = "Cobblestone"
		Parent.Text = "Material: Cobblestone"
		Toggle = false
		Select()
	end)
	Material.Air.MouseButton1Click:Connect(function()
		handle.Material = "Air"
		Parent.Text = "Material: Air"
		Toggle = false
		Select()
	end)
	Material.Water.MouseButton1Click:Connect(function()
		handle.Material = "Water"
		Parent.Text = "Material: Water"
		Toggle = false
		Select()
	end)
	Material.Rock.MouseButton1Click:Connect(function()
		handle.Material = "Rock"
		Parent.Text = "Material: Rock"
		Toggle = false
		Select()
	end)
	Material.Glacier.MouseButton1Click:Connect(function()
		handle.Material = "Glacier"
		Parent.Text = "Material: Glacier"
		Toggle = false
		Select()
	end)
	Material.Snow.MouseButton1Click:Connect(function()
		handle.Material = "Snow"
		Parent.Text = "Material: Snow"
		Toggle = false
		Select()
	end)
	Material.Sandstone.MouseButton1Click:Connect(function()
		handle.Material = "Sandstone"
		Parent.Text = "Material: Sandstone"
		Toggle = false
		Select()
	end)
	Material.Mud.MouseButton1Click:Connect(function()
		handle.Material = "Mud"
		Parent.Text = "Material: Mud"
		Toggle = false
		Select()
	end)
	Material.Basalt.MouseButton1Click:Connect(function()
		handle.Material = "Basalt"
		Parent.Text = "Material: Basalt"
		Toggle = false
		Select()
	end)
	Material.Ground.MouseButton1Click:Connect(function()
		handle.Material = "Ground"
		Parent.Text = "Material: Ground"
		Toggle = false
		Select()
	end)
	Material.CrackedLava.MouseButton1Click:Connect(function()
		handle.Material = "CrackedLava"
		Parent.Text = "Material: CrackedLava"
		Toggle = false
		Select()
	end)
	Material.Neon.MouseButton1Click:Connect(function()
		handle.Material = "Neon"
		Parent.Text = "Material: Neon"
		Toggle = false
		Select()
	end)
	Material.Glass.MouseButton1Click:Connect(function()
		handle.Material = "Glass"
		Parent.Text = "Material: Glass"
		Toggle = false
		Select()
	end)
	Material.Asphalt.MouseButton1Click:Connect(function()
		handle.Material = "Asphalt"
		Parent.Text = "Material: Asphalt"
		Toggle = false
		Select()
	end)
	Material.LeafyGrass.MouseButton1Click:Connect(function()
		handle.Material = "LeafyGrass"
		Parent.Text = "Material: LeafyGrass"
		Toggle = false
		Select()
	end)
	Material.Salt.MouseButton1Click:Connect(function()
		handle.Material = "Salt"
		Parent.Text = "Material: Salt"
		Toggle = false
		Select()
	end)
	Material.Limestone.MouseButton1Click:Connect(function()
		handle.Material = "Limestone"
		Parent.Text = "Material: Limestone"
		Toggle = false
		Select()
	end)
	Material.Pavement.MouseButton1Click:Connect(function()
		handle.Material = "Pavement"
		Parent.Text = "Material: Pavement"
		Toggle = false
		Select()
	end)
	Material.ForceField.MouseButton1Click:Connect(function()
		handle.Material = "ForceField"
		Parent.Text = "Material: ForceField"
		Toggle = false
		Select()
	end)
end
coroutine.wrap(DUYHYT_fake_script)()
local function WJNRSSS_fake_script() -- BallMaterial.Ball Material script 
	local script = Instance.new('LocalScript', BallMaterial)

	local Material = script.Parent.Parent.Parent["Ball Material Select"]
	local LocalPlayer = game.Players.LocalPlayer.Name
	local Parent = script.Parent
	local ball = game.Workspace.playerModels:WaitForChild(LocalPlayer).ball
	local Toggle = false
	
	
	script.Parent.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Select()
	end)
	
	function Select()
		if Toggle then
			Material.Visible = true
		else
			Material.Visible = false
		end
	end
	
	
	Material.Default.MouseButton1Click:Connect(function()
		ball.Material = "Plastic"
		Parent.Text = "Material: Default"
		Toggle = false	
		Select()
	end)
	Material.Plastic.MouseButton1Click:Connect(function()
		ball.Material = "Plastic"
		Parent.Text = "Material: Plastic"
		Toggle = false
		Select()
	end)
	Material.Wood.MouseButton1Click:Connect(function()
		ball.Material = "Wood"
		Parent.Text = "Material: Wood"
		Toggle = false
		Select()
	end)
	Material.Slate.MouseButton1Click:Connect(function()
		ball.Material = "Slate"
		Parent.Text = "Material: Slate"
		Toggle = false
		Select()
	end)
	Material.Concrete.MouseButton1Click:Connect(function()
		ball.Material = "Concrete"
		Parent.Text = "Material: Concrete"
		Toggle = false
		Select()
	end)
	Material.CorrodedMetal.MouseButton1Click:Connect(function()
		ball.Material = "CorrodedMetal"
		Parent.Text = "Material: CorrodedMetal"
		Toggle = false
		Select()
	end)
	Material.DiamondPlate.MouseButton1Click:Connect(function()
		ball.Material = "DiamondPlate"
		Parent.Text = "Material: DiamondPlate"
		Toggle = false
		Select()
	end)
	Material.Foil.MouseButton1Click:Connect(function()
		ball.Material = "Foil"
		Parent.Text = "Material: Foil"
		Toggle = false
		Select()
	end)
	Material.Grass.MouseButton1Click:Connect(function()
		ball.Material = "Grass"
		Parent.Text = "Material: Grass"
		Toggle = false
		Select()
	end)
	Material.Ice.MouseButton1Click:Connect(function()
		ball.Material = "Ice"
		Parent.Text = "Material: Ice"
		Toggle = false
		Select()
	end)
	Material.Marble.MouseButton1Click:Connect(function()
		ball.Material = "Marble"
		Parent.Text = "Material: Marble"
		Toggle = false
		Select()
	end)
	Material.Granite.MouseButton1Click:Connect(function()
		ball.Material = "Granite"
		Parent.Text = "Material: Granite"
		Toggle = false
		Select()
	end)
	Material.Brick.MouseButton1Click:Connect(function()
		ball.Material = "Brick"
		Parent.Text = "Material: Brick"
		Toggle = false
		Select()
	end)
	Material.Pebble.MouseButton1Click:Connect(function()
		ball.Material = "Pebble"
		Parent.Text = "Material: Pebble"
		Toggle = false
		Select()
	end)
	Material.Sand.MouseButton1Click:Connect(function()
		ball.Material = "Sand"
		Parent.Text = "Material: Sand"
		Toggle = false
		Select()
	end)
	Material.Fabric.MouseButton1Click:Connect(function()
		ball.Material = "Fabric"
		Parent.Text = "Material: Fabric"
		Toggle = false
		Select()
	end)
	Material.SmoothPlastic.MouseButton1Click:Connect(function()
		ball.Material = "SmoothPlastic"
		Parent.Text = "Material: SmoothPlastic"
		Toggle = false
		Select()
	end)
	Material.Metal.MouseButton1Click:Connect(function()
		ball.Material = "Metal"
		Parent.Text = "Material: Metal"
		Toggle = false
		Select()
	end)
	Material.WoodPlanks.MouseButton1Click:Connect(function()
		ball.Material = "WoodPlanks"
		Parent.Text = "Material: WoodPlanks"
		Toggle = false
		Select()
	end)
	Material.Cobblestone.MouseButton1Click:Connect(function()
		ball.Material = "Cobblestone"
		Parent.Text = "Material: Cobblestone"
		Toggle = false
		Select()
	end)
	Material.Air.MouseButton1Click:Connect(function()
		ball.Material = "Air"
		Parent.Text = "Material: Air"
		Toggle = false
		Select()
	end)
	Material.Water.MouseButton1Click:Connect(function()
		ball.Material = "Water"
		Parent.Text = "Material: Water"
		Toggle = false
		Select()
	end)
	Material.Rock.MouseButton1Click:Connect(function()
		ball.Material = "Rock"
		Parent.Text = "Material: Rock"
		Toggle = false
		Select()
	end)
	Material.Glacier.MouseButton1Click:Connect(function()
		ball.Material = "Glacier"
		Parent.Text = "Material: Glacier"
		Toggle = false
		Select()
	end)
	Material.Snow.MouseButton1Click:Connect(function()
		ball.Material = "Snow"
		Parent.Text = "Material: Snow"
		Toggle = false
		Select()
	end)
	Material.Sandstone.MouseButton1Click:Connect(function()
		ball.Material = "Sandstone"
		Parent.Text = "Material: Sandstone"
		Toggle = false
		Select()
	end)
	Material.Mud.MouseButton1Click:Connect(function()
		ball.Material = "Mud"
		Parent.Text = "Material: Mud"
		Toggle = false
		Select()
	end)
	Material.Basalt.MouseButton1Click:Connect(function()
		ball.Material = "Basalt"
		Parent.Text = "Material: Basalt"
		Toggle = false
		Select()
	end)
	Material.Ground.MouseButton1Click:Connect(function()
		ball.Material = "Ground"
		Parent.Text = "Material: Ground"
		Toggle = false
		Select()
	end)
	Material.CrackedLava.MouseButton1Click:Connect(function()
		ball.Material = "CrackedLava"
		Parent.Text = "Material: CrackedLava"
		Toggle = false
		Select()
	end)
	Material.Neon.MouseButton1Click:Connect(function()
		ball.Material = "Neon"
		Parent.Text = "Material: Neon"
		Toggle = false
		Select()
	end)
	Material.Glass.MouseButton1Click:Connect(function()
		ball.Material = "Glass"
		Parent.Text = "Material: Glass"
		Toggle = false
		Select()
	end)
	Material.Asphalt.MouseButton1Click:Connect(function()
		ball.Material = "Asphalt"
		Parent.Text = "Material: Asphalt"
		Toggle = false
		Select()
	end)
	Material.LeafyGrass.MouseButton1Click:Connect(function()
		ball.Material = "LeafyGrass"
		Parent.Text = "Material: LeafyGrass"
		Toggle = false
		Select()
	end)
	Material.Salt.MouseButton1Click:Connect(function()
		ball.Material = "Salt"
		Parent.Text = "Material: Salt"
		Toggle = false
		Select()
	end)
	Material.Limestone.MouseButton1Click:Connect(function()
		ball.Material = "Limestone"
		Parent.Text = "Material: Limestone"
		Toggle = false
		Select()
	end)
	Material.Pavement.MouseButton1Click:Connect(function()
		ball.Material = "Pavement"
		Parent.Text = "Material: Pavement"
		Toggle = false
		Select()
	end)
	Material.ForceField.MouseButton1Click:Connect(function()
		ball.Material = "ForceField"
		Parent.Text = "Material: ForceField"
		Toggle = false
		Select()
	end)
end
coroutine.wrap(WJNRSSS_fake_script)()
local function DAXG_fake_script() -- BallColor.Ball Color script 
	local script = Instance.new('LocalScript', BallColor)

	local Color = script.Parent.Parent.Parent["Ball Color Select"]
	local LocalPlayer = game.Players.LocalPlayer.Name
	local Parent = script.Parent
	local ball = game.Workspace.playerModels:WaitForChild(LocalPlayer).ball
	
	script.Parent.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Select()
	end)
	
	function Select()
		if Toggle then
			Color.Visible = true
		else
			Color.Visible = false
		end
	end
	
	Color.White.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(1, 1, 1)
		Parent.Text = "Color: White"
		Toggle = false
		Select()
	end)
	Color.Red.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(1, 0, 0)
		Parent.Text = "Color: Red"
		Toggle = false
		Select()
	end)
	Color.Crimson.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0.47451, 0, 0)
		Parent.Text = "Color: Crimson"
		Toggle = false
		Select()
	end)
	Color.Cyan.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0, 1, 1)
		Parent.Text = "Color: Cyan"
		Toggle = false
		Select()
	end)
	Color.Yellow.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(1, 1, 0)
		Parent.Text = "Color: Yellow"
		Toggle = false
		Select()
	end)
	Color.Green.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0, 0.439216, 0)
		Parent.Text = "Color: Green"
		Toggle = false
		Select()
	end)
	Color.Pink.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(1, 0, 1)
		Parent.Text = "Color: Pink"
		Toggle = false
		Select()
	end)
	Color.Purple.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0.470588, 0.117647, 1)
		Parent.Text = "Color: Purple"
		Toggle = false
		Select()
	end)
	Color.Blue.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0, 0, 1)
		Parent.Text = "Color: Blue"
		Toggle = false
		Select()
	end)
	Color.Lime.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0, 1, 0)
		Parent.Text = "Color: Lime"
		Toggle = false
		Select()
	end)
	Color.Gray.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0.317647, 0.317647, 0.317647)
		Parent.Text = "Color: Gray"
		Toggle = false
		Select()
	end)
	Color.Brown.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(0.560784, 0.380392, 0.12549)
		Parent.Text = "Color: Brown"
		Toggle = false
		Select()
	end)
	Color.Tan.MouseButton1Click:Connect(function()
		ball.Color = Color3.new(1, 0.709804, 0.470588)
		Parent.Text = "Color: Tan"
		Toggle = false
		Select()
	end)
end
coroutine.wrap(DAXG_fake_script)()
local function NGZNXT_fake_script() -- AxeColor.Axe Color script 
	local script = Instance.new('LocalScript', AxeColor)

	local Color = script.Parent.Parent.Parent["Axe Color Select"]
	local LocalPlayer = game.Players.LocalPlayer.Name
	local Parent = script.Parent
	local axe = game.Workspace.playerModels:WaitForChild(LocalPlayer).axe
	
	script.Parent.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Select()
	end)
	
	function Select()
		if Toggle then
			Color.Visible = true
		else
			Color.Visible = false
		end
	end
	
	Color.Default.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0.505882, 0.501961, 0.509804)
		Parent.Text = "Color: Default"
		Toggle = false
		Select()
	end)
	Color.White.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(1, 1, 1)
		Parent.Text = "Color: White"
		Toggle = false
		Select()
	end)
	Color.Red.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(1, 0, 0)
		Parent.Text = "Color: Red"
		Toggle = false
		Select()
	end)
	Color.Crimson.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0.47451, 0, 0)
		Parent.Text = "Color: Crimson"
		Toggle = false
		Select()
	end)
	Color.Cyan.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0, 1, 1)
		Parent.Text = "Color: Cyan"
		Toggle = false
		Select()
	end)
	Color.Yellow.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(1, 1, 0)
		Parent.Text = "Color: Yellow"
		Toggle = false
		Select()
	end)
	Color.Green.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0, 0.439216, 0)
		Parent.Text = "Color: Green"
		Toggle = false
		Select()
	end)
	Color.Pink.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(1, 0, 1)
		Parent.Text = "Color: Pink"
		Toggle = false
		Select()
	end)
	Color.Purple.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0.470588, 0.117647, 1)
		Parent.Text = "Color: Purple"
		Toggle = false
		Select()
	end)
	Color.Blue.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0, 0, 1)
		Parent.Text = "Color: Blue"
		Toggle = false
		Select()
	end)
	Color.Lime.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0, 1, 0)
		Parent.Text = "Color: Lime"
		Toggle = false
		Select()
	end)
	Color.Gray.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0.317647, 0.317647, 0.317647)
		Parent.Text = "Color: Gray"
		Toggle = false
		Select()
	end)
	Color.Brown.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(0.560784, 0.380392, 0.12549)
		Parent.Text = "Color: Brown"
		Toggle = false
		Select()
	end)
	Color.Tan.MouseButton1Click:Connect(function()
		axe.Color = Color3.new(1, 0.709804, 0.470588)
		Parent.Text = "Color: Tan"
		Toggle = false
		Select()
	end)
end
coroutine.wrap(NGZNXT_fake_script)()
local function RZVJS_fake_script() -- AxeMaterial.Axe Material script 
	local script = Instance.new('LocalScript', AxeMaterial)

	local Material = script.Parent.Parent.Parent["Axe Material Select"]
	local LocalPlayer = game.Players.LocalPlayer.Name
	local Parent = script.Parent
	local axe = game.Workspace.playerModels:WaitForChild(LocalPlayer).axe
	local Toggle = false
	
	
	script.Parent.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Select()
	end)
	
	function Select()
		if Toggle then
			Material.Visible = true
		else
			Material.Visible = false
		end
	end
	
	
	Material.Default.MouseButton1Click:Connect(function()
		axe.Material = "SmoothPlastic"
		Parent.Text = "Material: Default"
		Toggle = false	
		Select()
	end)
	Material.Plastic.MouseButton1Click:Connect(function()
		axe.Material = "Plastic"
		Parent.Text = "Material: Plastic"
		Toggle = false
		Select()
	end)
	Material.Wood.MouseButton1Click:Connect(function()
		axe.Material = "Wood"
		Parent.Text = "Material: Wood"
		Toggle = false
		Select()
	end)
	Material.Slate.MouseButton1Click:Connect(function()
		axe.Material = "Slate"
		Parent.Text = "Material: Slate"
		Toggle = false
		Select()
	end)
	Material.Concrete.MouseButton1Click:Connect(function()
		axe.Material = "Concrete"
		Parent.Text = "Material: Concrete"
		Toggle = false
		Select()
	end)
	Material.CorrodedMetal.MouseButton1Click:Connect(function()
		axe.Material = "CorrodedMetal"
		Parent.Text = "Material: CorrodedMetal"
		Toggle = false
		Select()
	end)
	Material.DiamondPlate.MouseButton1Click:Connect(function()
		axe.Material = "DiamondPlate"
		Parent.Text = "Material: DiamondPlate"
		Toggle = false
		Select()
	end)
	Material.Foil.MouseButton1Click:Connect(function()
		axe.Material = "Foil"
		Parent.Text = "Material: Foil"
		Toggle = false
		Select()
	end)
	Material.Grass.MouseButton1Click:Connect(function()
		axe.Material = "Grass"
		Parent.Text = "Material: Grass"
		Toggle = false
		Select()
	end)
	Material.Ice.MouseButton1Click:Connect(function()
		axe.Material = "Ice"
		Parent.Text = "Material: Ice"
		Toggle = false
		Select()
	end)
	Material.Marble.MouseButton1Click:Connect(function()
		axe.Material = "Marble"
		Parent.Text = "Material: Marble"
		Toggle = false
		Select()
	end)
	Material.Granite.MouseButton1Click:Connect(function()
		axe.Material = "Granite"
		Parent.Text = "Material: Granite"
		Toggle = false
		Select()
	end)
	Material.Brick.MouseButton1Click:Connect(function()
		axe.Material = "Brick"
		Parent.Text = "Material: Brick"
		Toggle = false
		Select()
	end)
	Material.Pebble.MouseButton1Click:Connect(function()
		axe.Material = "Pebble"
		Parent.Text = "Material: Pebble"
		Toggle = false
		Select()
	end)
	Material.Sand.MouseButton1Click:Connect(function()
		axe.Material = "Sand"
		Parent.Text = "Material: Sand"
		Toggle = false
		Select()
	end)
	Material.Fabric.MouseButton1Click:Connect(function()
		axe.Material = "Fabric"
		Parent.Text = "Material: Fabric"
		Toggle = false
		Select()
	end)
	Material.SmoothPlastic.MouseButton1Click:Connect(function()
		axe.Material = "SmoothPlastic"
		Parent.Text = "Material: SmoothPlastic"
		Toggle = false
		Select()
	end)
	Material.Metal.MouseButton1Click:Connect(function()
		axe.Material = "Metal"
		Parent.Text = "Material: Metal"
		Toggle = false
		Select()
	end)
	Material.WoodPlanks.MouseButton1Click:Connect(function()
		axe.Material = "WoodPlanks"
		Parent.Text = "Material: WoodPlanks"
		Toggle = false
		Select()
	end)
	Material.Cobblestone.MouseButton1Click:Connect(function()
		axe.Material = "Cobblestone"
		Parent.Text = "Material: Cobblestone"
		Toggle = false
		Select()
	end)
	Material.Air.MouseButton1Click:Connect(function()
		axe.Material = "Air"
		Parent.Text = "Material: Air"
		Toggle = false
		Select()
	end)
	Material.Water.MouseButton1Click:Connect(function()
		axe.Material = "Water"
		Parent.Text = "Material: Water"
		Toggle = false
		Select()
	end)
	Material.Rock.MouseButton1Click:Connect(function()
		axe.Material = "Rock"
		Parent.Text = "Material: Rock"
		Toggle = false
		Select()
	end)
	Material.Glacier.MouseButton1Click:Connect(function()
		axe.Material = "Glacier"
		Parent.Text = "Material: Glacier"
		Toggle = false
		Select()
	end)
	Material.Snow.MouseButton1Click:Connect(function()
		axe.Material = "Snow"
		Parent.Text = "Material: Snow"
		Toggle = false
		Select()
	end)
	Material.Sandstone.MouseButton1Click:Connect(function()
		axe.Material = "Sandstone"
		Parent.Text = "Material: Sandstone"
		Toggle = false
		Select()
	end)
	Material.Mud.MouseButton1Click:Connect(function()
		axe.Material = "Mud"
		Parent.Text = "Material: Mud"
		Toggle = false
		Select()
	end)
	Material.Basalt.MouseButton1Click:Connect(function()
		axe.Material = "Basalt"
		Parent.Text = "Material: Basalt"
		Toggle = false
		Select()
	end)
	Material.Ground.MouseButton1Click:Connect(function()
		axe.Material = "Ground"
		Parent.Text = "Material: Ground"
		Toggle = false
		Select()
	end)
	Material.CrackedLava.MouseButton1Click:Connect(function()
		axe.Material = "CrackedLava"
		Parent.Text = "Material: CrackedLava"
		Toggle = false
		Select()
	end)
	Material.Neon.MouseButton1Click:Connect(function()
		axe.Material = "Neon"
		Parent.Text = "Material: Neon"
		Toggle = false
		Select()
	end)
	Material.Glass.MouseButton1Click:Connect(function()
		axe.Material = "Glass"
		Parent.Text = "Material: Glass"
		Toggle = false
		Select()
	end)
	Material.Asphalt.MouseButton1Click:Connect(function()
		axe.Material = "Asphalt"
		Parent.Text = "Material: Asphalt"
		Toggle = false
		Select()
	end)
	Material.LeafyGrass.MouseButton1Click:Connect(function()
		axe.Material = "LeafyGrass"
		Parent.Text = "Material: LeafyGrass"
		Toggle = false
		Select()
	end)
	Material.Salt.MouseButton1Click:Connect(function()
		axe.Material = "Salt"
		Parent.Text = "Material: Salt"
		Toggle = false
		Select()
	end)
	Material.Limestone.MouseButton1Click:Connect(function()
		axe.Material = "Limestone"
		Parent.Text = "Material: Limestone"
		Toggle = false
		Select()
	end)
	Material.Pavement.MouseButton1Click:Connect(function()
		axe.Material = "Pavement"
		Parent.Text = "Material: Pavement"
		Toggle = false
		Select()
	end)
	Material.ForceField.MouseButton1Click:Connect(function()
		axe.Material = "ForceField"
		Parent.Text = "Material: ForceField"
		Toggle = false
		Select()
	end)
end
coroutine.wrap(RZVJS_fake_script)()
local function VRHSRYC_fake_script() -- AxeHandleColor.Axe Handle Color script 
	local script = Instance.new('LocalScript', AxeHandleColor)

	local Color = script.Parent.Parent.Parent["Axe Handle Color Select"]
	local LocalPlayer = game.Players.LocalPlayer.Name
	local Parent = script.Parent
	local handle = game.Workspace.playerModels:WaitForChild(LocalPlayer).axe.handle
	
	script.Parent.MouseButton1Click:Connect(function()
		Toggle = not Toggle
		Select()
	end)
	
	function Select()
		if Toggle then
			Color.Visible = true
		else
			Color.Visible = false
		end
	end
	
	Color.Default.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0.623529, 0.537255, 0.403922)
		Parent.Text = "Color: Default"
		Toggle = false
		Select()
	end)
	Color.White.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(1, 1, 1)
		Parent.Text = "Color: White"
		Toggle = false
		Select()
	end)
	Color.Red.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(1, 0, 0)
		Parent.Text = "Color: Red"
		Toggle = false
		Select()
	end)
	Color.Crimson.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0.47451, 0, 0)
		Parent.Text = "Color: Crimson"
		Toggle = false
		Select()
	end)
	Color.Cyan.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0, 1, 1)
		Parent.Text = "Color: Cyan"
		Toggle = false
		Select()
	end)
	Color.Yellow.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(1, 1, 0)
		Parent.Text = "Color: Yellow"
		Toggle = false
		Select()
	end)
	Color.Green.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0, 0.439216, 0)
		Parent.Text = "Color: Green"
		Toggle = false
		Select()
	end)
	Color.Pink.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(1, 0, 1)
		Parent.Text = "Color: Pink"
		Toggle = false
		Select()
	end)
	Color.Purple.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0.470588, 0.117647, 1)
		Parent.Text = "Color: Purple"
		Toggle = false
		Select()
	end)
	Color.Blue.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0, 0, 1)
		Parent.Text = "Color: Blue"
		Toggle = false
		Select()
	end)
	Color.Lime.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0, 1, 0)
		Parent.Text = "Color: Lime"
		Toggle = false
		Select()
	end)
	Color.Gray.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0.317647, 0.317647, 0.317647)
		Parent.Text = "Color: Gray"
		Toggle = false
		Select()
	end)
	Color.Brown.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(0.560784, 0.380392, 0.12549)
		Parent.Text = "Color: Brown"
		Toggle = false
		Select()
	end)
	Color.Tan.MouseButton1Click:Connect(function()
		handle.Color = Color3.new(1, 0.709804, 0.470588)
		Parent.Text = "Color: Tan"
		Toggle = false
		Select()
	end)
end
coroutine.wrap(VRHSRYC_fake_script)()
local function XFURQM_fake_script() -- BallMaterialSelect.Draggable 
	local script = Instance.new('LocalScript', BallMaterialSelect)

	script.Parent.Draggable = true
end
coroutine.wrap(XFURQM_fake_script)()
local function RJVO_fake_script() -- AxeMaterialSelect.Draggable 
	local script = Instance.new('LocalScript', AxeMaterialSelect)

	script.Parent.Draggable = true
end
coroutine.wrap(RJVO_fake_script)()
local function BODJ_fake_script() -- AxeHandleMaterialSelect.Draggable 
	local script = Instance.new('LocalScript', AxeHandleMaterialSelect)

	script.Parent.Draggable = true
end
coroutine.wrap(BODJ_fake_script)()
local function UCFI_fake_script() -- BallColorSelect.Draggable 
	local script = Instance.new('LocalScript', BallColorSelect)

	script.Parent.Draggable = true
end
coroutine.wrap(UCFI_fake_script)()
local function TXTMIR_fake_script() -- AxeHandleColorSelect.Draggable 
	local script = Instance.new('LocalScript', AxeHandleColorSelect)

	script.Parent.Draggable = true
end
coroutine.wrap(TXTMIR_fake_script)()
local function KZNQ_fake_script() -- AxeColorSelect.Draggable 
	local script = Instance.new('LocalScript', AxeColorSelect)

	script.Parent.Draggable = true
end
coroutine.wrap(KZNQ_fake_script)()=
